// Command genstructure regenerates the Go-authored StructureSig fixture set.
package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"ledger/internal/v2/diag"
)

type corpus struct {
	Cases []struct {
		Name string `json:"name"`
		Body string `json:"normalized_body_base64"`
	} `json:"cases"`
}
type vector struct {
	Name   string `json:"name"`
	Source string `json:"source"`
	Sig    string `json:"sig"`
}

func main() {
	if len(os.Args) != 2 {
		panic("usage: genstructure OUTPUT")
	}
	sources := []string{
		"conformance/templates/corpus-dib.account.v1.json",
		"conformance/templates/corpus-dib.card.v1.json",
		"conformance/templates/corpus-enbd.alert.v1.json",
	}
	out := struct {
		Note          string   `json:"note"`
		SchemaVersion int      `json:"schema_version"`
		Cases         []vector `json:"cases"`
	}{
		Note:          "Generated by internal/v2/diag/cmd/genstructure from normalized real-corpus bodies. Expectations are literal Go StructureSig output.",
		SchemaVersion: 1,
	}
	for _, source := range sources {
		b, err := os.ReadFile(source)
		if err != nil {
			panic(err)
		}
		var c corpus
		if err := json.Unmarshal(b, &c); err != nil {
			panic(err)
		}
		for _, item := range c.Cases {
			raw, err := base64.StdEncoding.DecodeString(item.Body)
			if err != nil {
				panic(err)
			}
			out.Cases = append(out.Cases, vector{Name: item.Name, Source: source, Sig: diag.StructureSig(string(raw))})
		}
	}
	b, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		panic(err)
	}
	b = append(b, '\n')
	if err := os.MkdirAll(filepath.Dir(os.Args[1]), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(os.Args[1], b, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %d vectors to %s\n", len(out.Cases), os.Args[1])
}
