-- +goose Up

-- Which credential authenticated a session.
--
-- `sessions` has been (token_hash, user_id, created_at, expires_at, revoked_at)
-- since 00001 and has never recorded WHICH passkey finished the ceremony that
-- minted it. Two things shipped wrong in 99f49c0 because of that, both
-- documented honestly at the time and both fixed by this one column:
--
--   * GET /api/v1/auth/passkeys could not mark the credential the caller is
--     standing on, so `current` was hard-coded false. Inferring it — matching
--     webauthn_credentials.last_used_at against sessions.created_at — was
--     deliberately refused, because re-authentication and any later sign-in
--     both break the inference and a WRONG "this device" marker is worse than
--     no marker at all.
--   * DELETE /api/v1/auth/passkeys/{id} could not tell the removed
--     credential's sessions from anybody else's, so it revoked every session
--     of the account except the caller's. "Remove my lost phone" signed the
--     user's laptop out too.
--
-- # Nullable, and that is a requirement rather than laziness
--
-- Every session that exists at the moment this migration runs was minted before
-- anything recorded a credential, and there is NO WAY to attribute one after
-- the fact. The candidate signal — a credential whose last_used_at is close to
-- the session's created_at — is exactly the inference the listing refused to
-- make, and writing it into a column would launder a guess into a stored fact
-- that the revocation path then acts on. So existing rows keep NULL, NULL means
-- "this server does not know", and both readers are written to treat it as an
-- absence of knowledge:
--
--   * the listing shows no marker at all for an unattributed session, never a
--     wrong one;
--   * the removal revokes an unattributed session anyway (except the caller's
--     own), because "might belong to the credential being removed" is the one
--     case where erring towards signing a device out is the safe direction.
--     That over-reach shrinks to nothing on its own: it can only ever touch
--     sessions minted before this column existed or by the ID-token exchange,
--     and every session has a TTL.
--
-- The column is also NULL for the ID-token exchange path (POST /api/v1/auth/
-- exchange, Apple/Google), which authenticates no credential and must not
-- pretend it did.
--
-- # ON DELETE SET NULL, deliberately, and NOT ON DELETE CASCADE
--
-- CASCADE would DELETE the session row when the credential is removed. Deleting
-- a session and revoking a session are different facts here, and three separate
-- pieces of this system depend on the row surviving:
--
--  1. auth.Sessions.Resolve answers ErrSessionRevoked for a row with revoked_at
--     set and ErrSessionUnknown for a row that is gone. RevokeAllForUser's doc
--     states why rows are marked and not deleted: it is the difference between
--     a log line that says "someone is using a revoked credential" and one that
--     says "someone typed garbage". A cascade would silently convert every
--     passkey removal into the second.
--
--  2. 00021's BEFORE DELETE trigger on `users` tombstones the account's LIVE
--     sessions rows into deleted_account_sessions, which is the only way a
--     device ever learns 410 "this account is gone" instead of 401 "sign in
--     again" — and 410 is the only answer that makes a client wipe its local
--     ledger. A session row already cascaded away by a credential removal is
--     never tombstoned, so that device would sit on 401 for ever and never
--     wipe. That is precisely the failure 00021 exists to prevent, reintroduced
--     through a different door.
--
--  3. forgetPushTokens keys push_tokens/push_subscriptions off session_hash, in
--     the same transaction as the revocation. A DB-level cascade fires beneath
--     Go entirely, so any future path that deletes a credential without going
--     through auth.Passkeys.DeleteCredential would drop the session row and
--     leave its push registrations behind — a phone that can no longer write
--     but keeps showing "New transaction" on its lock screen.
--
-- SET NULL keeps the row, keeps revoked_at meaningful, keeps the tombstone
-- reachable, and leaves the column doing the one job a foreign key is here for:
-- guaranteeing it never names a credential that no longer exists.
--
-- Ordering note for the code that relies on this: auth.Passkeys.DeleteCredential
-- REVOKES the credential's sessions BEFORE deleting the credential row, in one
-- transaction. After the DELETE the attribution is gone (that is what SET NULL
-- means), so a revocation issued afterwards would match nothing.
--
-- # Why the foreign key is not composite
--
-- (user_id, credential_id) REFERENCES webauthn_credentials(user_id,
-- credential_id) would have the schema enforce that a session's credential
-- belongs to the session's own account. It is not used because SET NULL on a
-- composite key nulls EVERY column of the key, and sessions.user_id is NOT NULL
-- — the referential action would fail outright. Postgres 15+ can name a column
-- subset (ON DELETE SET NULL (credential_id)), but relying on that syntax buys
-- a constraint that the write path already guarantees: the only writer is
-- auth.Sessions.IssueForCredential, called with the credential the ceremony
-- just verified for exactly that account.
--
-- # Grants
--
-- 00003_writers.sql's two-role recipe does NOT apply here. That block exists for
-- migrations that CREATE a table, which a fresh table needs because
-- ledger_runtime's privileges were granted per-table (plus ALTER DEFAULT
-- PRIVILEGES for future ones). This migration only ALTERs a table that already
-- exists, and Postgres table-level privileges are not per-column: the
-- SELECT/INSERT/UPDATE/DELETE ledger_runtime already holds on `sessions` covers
-- the new column and the new index the moment they exist. No GRANT is needed and
-- adding one would imply otherwise.

ALTER TABLE sessions
  ADD COLUMN credential_id bytea
    REFERENCES webauthn_credentials(credential_id) ON DELETE SET NULL;

-- Serves the revocation's `WHERE user_id = $1 AND credential_id = $2` and, more
-- importantly, the referential action itself: without an index on the
-- REFERENCING column, every credential removal scans all of `sessions` to find
-- the rows to null out.
CREATE INDEX sessions_credential_idx ON sessions (credential_id)
  WHERE credential_id IS NOT NULL;

-- +goose Down
DROP INDEX sessions_credential_idx;
ALTER TABLE sessions DROP COLUMN credential_id;
