package oplog

// conformance_test.go is the shared-bytes half of the dual-executor contract.
//
// Spec §3.5 mandates two independent executors — this Go one and the TypeScript
// one in client/ — and says a disagreement fails the build. Two implementations
// that only ever test themselves cannot disagree, so the agreement is made
// mechanical here: this file WRITES a set of fixtures from the Go encoders and
// then, on every run, RE-READS them and asserts this build still agrees with
// them. The TypeScript side reads exactly the same files.
//
// # Why the fixtures live here and not in package blob
//
// The plan put the fixture writer in internal/v2/blob. It cannot live there:
// oplog imports blob, so blob cannot import oplog, and a blob-package writer
// would have to carry a hand-copied literal of the op JSON — a second copy of a
// frozen wire format, which is the exact failure mode fixtures exist to prevent.
// Written here, every fixture's plaintext comes out of the real EncodeBlob and
// EncodeRawBody, and goldenOps is shared with TestGoldenOpBytes so there is one
// literal in the repository, not two.
//
// # Three directions are covered, and each catches something different
//
//  1. conformance/blob + conformance/op are written BY Go and read BY both.
//     TestConformanceFixturesAreWhatThisBuildProduces re-opens them here; the
//     TypeScript blob.test.ts/op.test.ts open the same bytes. A change to the
//     framing, the bucket ladder, the AAD field set or the op JSON breaks
//     whichever side moved.
//
//  2. conformance/ts is written BY TypeScript (client/scripts/gen-fixtures.ts)
//     and read here by TestTypeScriptSealedBlobsOpenInGo. That is the direction
//     a fixture set alone always misses: a TS port that decodes Go's bytes
//     perfectly and emits subtly wrong ones would pass every test in group 1.
//     It is also the direction the server sees, since a device uploads blobs it
//     sealed itself.
//
//  3. The parsed-instant cases in conformance/op/manifest.json pin the
//     millisecond rule (canonicalTime) as a set of (wire string, unix
//     milliseconds) pairs generated by THIS decoder. Comparing instants rather
//     than strings is deliberate: Go's RFC3339Nano trims trailing zeros where
//     JavaScript's toISOString always pads to three digits, so the two encoders
//     are byte-different and instant-identical, and only the second is claimed.
//
//     That instants-only rule had a hole, and it was live. A timestamp's
//     canonical FORM can leave the grammar both decoders enforce — the wire
//     admits a four-digit year with an offset up to ±23:59, so year 10000 and
//     year −1 are both reachable — and the two languages do not spell the
//     overflow the same way (10000-01-01T… against +010000-01-01T…). Every
//     assertion here compared parsed instants, and the divergence is in a string
//     neither side can parse, so the suite was structurally unable to see it:
//     Go accepted both boundary values and TypeScript refused them, for as long
//     as the contract has existed. Each case therefore also carries
//     expect_canonical_wire — the string THIS executor writes, which the
//     TypeScript side reads back — and the two boundary values are in
//     authored_at_rejects. See TestCanonicalTimeIsClosedOverTheWireGrammar and
//     TestTheExpandedYearRangeIsRefusedByBothExecutors.
//
// # What is deliberately NOT asserted
//
// That re-sealing a fixture reproduces its stored bytes. Sealing gzips, and
// gzip output is a property of the compressor rather than of the format: a Go
// release that retunes compress/flate would fail such a check while breaking
// nothing (every stored blob still opens, because gunzip does not care which
// encoder produced the stream). The durable claim is the one asserted below —
// the committed bytes still OPEN to the pinned plaintext, in both languages.

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	"ledger/internal/v2/blob"
)

// writeFixturesEnv gates the writer. A test that rewrites its own reference on
// every run pins nothing — it would silently re-bless whatever the code now
// produces, which is the one thing a golden file exists to prevent — so writing
// is opt-in and the fixtures are committed.
const writeFixturesEnv = "LEDGER_WRITE_CONFORMANCE"

// conformanceUser is the user id every fixture is sealed for. It is the same
// value package blob's own tests use, so a fixture's AAD is readable at a glance.
var conformanceUser = uuid.MustParse("11111111-1111-1111-1111-111111111111")

// ---------------------------------------------------------------------------
// The manifest shapes. Every integer that is an int64 on the wire is a decimal
// STRING here for the same reason it is one in the op model: a JSON number
// parsed by JavaScript is a float64.
// ---------------------------------------------------------------------------

type fixtureEnvelope struct {
	UserID        string `json:"user_id"`
	Stream        string `json:"stream"`
	WriterID      string `json:"writer_id"`
	WriterCounter string `json:"writer_counter"`
}

func (e fixtureEnvelope) blobEnvelope(t *testing.T) blob.Envelope {
	t.Helper()
	id, err := uuid.Parse(e.UserID)
	if err != nil {
		t.Fatalf("fixture envelope has an unparseable user id %q: %v", e.UserID, err)
	}
	counter, err := strconv.ParseInt(e.WriterCounter, 10, 64)
	if err != nil {
		t.Fatalf("fixture envelope has an unparseable counter %q: %v", e.WriterCounter, err)
	}
	return blob.Envelope{UserID: id, Stream: e.Stream, WriterID: e.WriterID, WriterCounter: counter}
}

type blobFixture struct {
	File                  string          `json:"file"`
	Note                  string          `json:"note"`
	Kind                  string          `json:"kind"` // KindOps or KindRawBody
	Envelope              fixtureEnvelope `json:"envelope"`
	ExpectAAD             string          `json:"expect_aad"`
	ExpectBucket          int             `json:"expect_bucket"`
	ExpectPlaintextBase64 string          `json:"expect_plaintext_base64"`
	// ExpectPrePadLength is the framed length before bucket padding. It is what
	// makes the boundary fixture a boundary fixture, and it is unreadable from
	// the padded bytes without walking the framing — which is the point.
	ExpectPrePadLength int `json:"expect_pre_pad_length"`
}

type chainStep struct {
	FillByte   string `json:"fill_byte"` // one hex byte, repeated
	Length     int    `json:"length"`
	ExpectHash string `json:"expect_hash"` // hex; SHA256(prev || bytes)
}

type blobManifest struct {
	Note        string        `json:"note"`
	Buckets     []int         `json:"buckets"`
	NonceSize   int           `json:"nonce_size"`
	TagSize     int           `json:"tag_size"`
	ZeroHashHex string        `json:"zero_hash_hex"`
	ChainSteps  []chainStep   `json:"chain_steps"`
	Fixtures    []blobFixture `json:"fixtures"`
}

type opExpect struct {
	Type             string `json:"type"`
	OpID             string `json:"op_id"`
	AuthoredAtUnixMs string `json:"authored_at_unix_ms"`
	HasEntity        bool   `json:"has_entity"`
	// ParentVersion is a decimal string or null, mirroring the ambiguity the
	// wire deliberately does not have: on the wire parent_version is a raw JSON
	// NUMBER (see the note in the manifest), but a manifest that repeated that
	// choice could not express a value above 2^53 for the TypeScript reader to
	// check itself against.
	ParentVersion *string `json:"parent_version"`
	IngestID      string  `json:"ingest_id"`
}

type timeCase struct {
	Wire         string `json:"wire"`
	ExpectUnixMs string `json:"expect_unix_ms"`
	// ExpectCanonicalWire is what THIS executor renders the canonical form as:
	// oplog.CanonicalWireTime, i.e. the string a Go writer puts on the wire.
	//
	// It is the one place the manifest pins a timestamp STRING, and the reason
	// is narrow. The header note is right that the two encoders are byte-
	// different and only the instant is claimed — Go trims trailing zeros where
	// toISOString pads to three digits — so this is NOT asserted to equal the
	// TypeScript rendering. What the TypeScript side asserts is that it can READ
	// this string, to the same instant: before this field existed, no test on
	// either side ever handed one executor a timestamp the other had actually
	// written, so a canonical form outside the shared grammar (year 10000 and
	// year −1 are both reachable from a wire-legal input) was invisible to the
	// whole suite. Go's own half is a golden pin: the value must still be what
	// this build produces, so a change to Go's spelling fails here.
	ExpectCanonicalWire string `json:"expect_canonical_wire"`
}

type opManifest struct {
	Note                                string            `json:"note"`
	SchemaVersion                       int               `json:"schema_version"`
	Types                               []string          `json:"types"`
	ParentFree                          []string          `json:"parent_free"`
	GoldenOpsBase64                     string            `json:"golden_ops_base64"`
	GoldenRawBodyBase64                 string            `json:"golden_raw_body_base64"`
	GoldenCheckpointBase64              string            `json:"golden_checkpoint_base64"`
	DuplicateDispositionBase64          string            `json:"duplicate_disposition_base64"`
	VerifiedOriginBase64                string            `json:"verified_origin_base64"`
	DuplicateDispositionInvalidPayloads []json.RawMessage `json:"duplicate_disposition_invalid_payloads"`
	ExpectOps                           []opExpect        `json:"expect_ops"`
	AuthoredAtCases                     []timeCase        `json:"authored_at_cases"`
	// ParentVersionOverflowBase64 is an op blob this executor accepts and the
	// TypeScript one must REFUSE: parent_version is a raw JSON number on the
	// frozen wire, so an int64 above 2^53 is expressible here and is already
	// rounded by JSON.parse before any TypeScript code sees it. The asymmetry is
	// a property of the format, not a bug in either port, so it is pinned as a
	// shared artifact rather than asserted from an inline literal on one side.
	ParentVersionOverflowBase64 string `json:"parent_version_overflow_base64"`
	// ParentVersionOverflow is that same value as a decimal string, which is the
	// only way this manifest can state it without being lossy itself.
	ParentVersionOverflow string `json:"parent_version_overflow"`
	// AuthoredAtRejects are timestamps BOTH executors must refuse. It is a
	// shared artifact rather than two independent literals on purpose: the whole
	// class of bug here is one side quietly accepting what the other refuses, and
	// two hand-maintained lists drift into exactly that.
	AuthoredAtRejects []string `json:"authored_at_rejects"`
}

// timeAcceptCases are timestamps both executors must read as the same instant,
// AND whose canonical form both executors can write and read back (see
// TestCanonicalTimeIsClosedOverTheWireGrammar).
var timeAcceptCases = []string{
	"2026-06-05T10:00:00Z",
	"2026-06-05T10:00:00.1Z",
	"2026-06-05T10:00:00.0015Z",    // truncates to 1ms, never rounds to 2
	"2026-06-05T10:00:00.0000015Z", // finer than a JS Date can hold
	"2026-06-05T14:00:00.5+04:00",
	"2026-06-05T10:00:00-00:00",
	"2026-06-05T10:00:00+23:59", // the largest offset both accept
	"2024-02-29T00:00:00Z",      // a real leap day
	"2000-02-29T00:00:00Z",      // divisible by 400

	// The four-digit-year range, at both ends and just inside. These are the
	// legal neighbours of the two rejects below: without them "refuses year
	// 10000" is indistinguishable from "refuses anything near the boundary",
	// and a fix that clamped the whole millennium would pass.
	"0000-01-01T00:00:00Z",     // the earliest instant the grammar can express
	"9999-12-31T23:59:59.999Z", // the latest
	"0000-02-29T00:00:00Z",     // year 0 IS a leap year: divisible by 400
	// Offsets that are not a whole or half hour, and the largest NEGATIVE one.
	// Only +23:59 was pinned, so the sign that actually crosses the upper year
	// boundary was the untested one.
	"2026-06-05T10:00:00+05:45", // Nepal
	"2026-06-05T10:00:00-09:30", // Marquesas
	"2026-06-05T10:00:00-23:59",
}

// timeRejectCases are timestamps both executors must refuse. Each was MEASURED
// against both runtimes; the comments name which side was the lenient one
// before this was pinned.
var timeRejectCases = []string{
	"2026-06-05T24:00:00Z",      // Date.parse rolled it to the next day
	"2026-02-30T10:00:00Z",      // Date.parse rolled it to MARCH 2nd
	"2026-02-29T00:00:00Z",      // 2026 is not a leap year
	"2026-13-05T10:00:00Z",      // month 13
	"2026-06-05T10:60:00Z",      // minute 60
	"2026-06-05T10:00:60Z",      // second 60: no leap seconds
	"2026-06-05T10:00:00+24:00", // stock Go accepted it; Date.parse refuses
	"2026-06-05T10:00:00+24:60", // stock Go read it as -25h
	"2026-06-05T10:00:00+00:60", // stock Go read it as -1h
	"2026-06-05t10:00:00z",      // Date.parse accepts lowercase; RFC3339 layout does not
	"2026-06-05 10:00:00Z",      // space separator
	"2026-06-05T10:00:00",       // no zone
	"2026-06-05T10:00:00.Z",     // empty fraction
	"0001-01-01T00:00:00Z",      // Go's zero time
	"2026-06-05",
	"June 5 2026",
	"",

	// The expanded-year boundary. These four are the case this file could not
	// see before, and each one dies if either executor's spelling changes.
	//
	// The first two are WIRE-LEGAL by every rule that existed: four-digit year,
	// offset within ±23:59, real calendar date. Their UTC value lands outside
	// years 0000-9999, which the grammar cannot express — and the two languages
	// spell that overflow differently (Go "10000-01-01T23:58:59Z", JavaScript
	// "+010000-01-01T23:58:59.000Z"). Go used to ACCEPT both and TypeScript to
	// refuse them, so the op was in one executor's log and in neither device's.
	"9999-12-31T23:59:59-23:59", // → year 10000
	"0000-01-01T00:00:00+00:01", // → year −1, the same defect at the bottom
	// And the two spellings offered back as INPUT. If either executor ever
	// learns to write one of these, it must not also learn to read it: an
	// expanded year on the wire is a blob the other executor sets aside.
	"+010000-01-01T23:58:59.000Z", // JavaScript's spelling
	"10000-01-01T23:58:59Z",       // Go's
	"-0001-12-31T23:59:00Z",       // a signed year, written literally

	// The negative twin of the +24:00 case. An offset is bounded at ±23:59 in
	// both directions, and only the positive bound was pinned.
	"2026-06-05T10:00:00-24:00",
}

// ---------------------------------------------------------------------------
// The fixtures themselves
// ---------------------------------------------------------------------------

func conformanceDir() string { return filepath.Join("..", "..", "..", "conformance") }

// goldenOps is the op set both TestGoldenOpBytes and the fixtures encode. One
// literal, two consumers: a change to it fails the golden byte comparison
// first, which is the readable failure.
func goldenOps() []Op {
	parent := int64(3)
	return []Op{
		// A create carrying an ingest_id: the only op shape in which that field
		// appears on the wire at all.
		{
			V:          1,
			Type:       OpTxnIngested,
			OpID:       "01J000000000000000000000I1",
			AuthoredAt: time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
			Entity:     &EntityRef{Kind: "txn", ID: "T1"},
			IngestID:   strings.Repeat("a", 64),
			Payload:    json.RawMessage(`{"amount_minor":"25000","currency":"AED"}`),
		},
		// A causal op with a parent version, which the wire carries as a raw
		// JSON number.
		{
			V:             1,
			Type:          OpTxnCategorized,
			OpID:          "01J000000000000000000000A1",
			AuthoredAt:    time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
			Entity:        &EntityRef{Kind: "txn", ID: "T1"},
			ParentVersion: &parent,
			Payload:       json.RawMessage(`{"category":"groceries"}`),
		},
		// A parent-free fact: no entity, null parent_version.
		{
			V:          1,
			Type:       OpRateSet,
			OpID:       "01J000000000000000000000R1",
			AuthoredAt: time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
			Payload:    json.RawMessage(`{"currency":"USD","rate_micro":"3672500"}`),
		},
	}
}

func duplicateDispositionOps() []Op {
	parent := int64(3)
	return []Op{{V: 2, Type: OpTxnDuplicateDisposition, OpID: "01J000000000000000000000D1",
		AuthoredAt: time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC), Entity: &EntityRef{Kind: "txn", ID: "T1"},
		ParentVersion: &parent, Payload: json.RawMessage(`{"other_txn_id":"T0","disposition":"same"}`)}}
}

func verifiedOriginOps() []Op {
	return []Op{{V: 2, Type: OpTxnIngested, OpID: "01J000000000000000000000O1",
		AuthoredAt: time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC), Entity: &EntityRef{Kind: "txn", ID: "T2"},
		IngestID: strings.Repeat("a", 64), Payload: json.RawMessage(`{"amount_minor":"1","currency":"AED","direction":"debit","posted_at":"2026-06-05T10:00:00Z","merchant_raw":"BANK","last4":"","needs_review":false,"unparsed":false,"tier":"template","verified_origin_domain":"bank.example"}`)}}
}

func mustEncodeBlob(t *testing.T, ops []Op) []byte {
	t.Helper()
	b, err := EncodeBlob(ops)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func goldenRawBody() RawBody {
	return RawBody{
		IngestID:   strings.Repeat("a", 64),
		ReceivedAt: time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
		RawBase64:  "aGk=",
	}
}

func goldenCheckpointHeads() []CheckpointHead {
	return []CheckpointHead{
		{WriterID: "ingest", Stream: "hot", Counter: "9", Hash: strings.Repeat("b", 64)},
		{WriterID: "dev-a", Stream: "hot", Counter: "12", Hash: strings.Repeat("c", 64)},
		{WriterID: "ingest", Stream: "cold", Counter: "9", Hash: strings.Repeat("d", 64)},
	}
}

// incompressibleBytes returns n bytes gzip cannot shrink, derived from a hash
// chain so the value is identical on every machine and every Go release. A
// math/rand stream is not: its algorithm is a documented implementation detail
// and the global source is randomly seeded since Go 1.20.
func incompressibleBytes(n int) []byte {
	out := make([]byte, 0, n+sha256.Size)
	var ctr [8]byte
	for i := uint64(0); len(out) < n; i++ {
		binary.BigEndian.PutUint64(ctr[:], i)
		sum := sha256.Sum256(ctr[:])
		out = append(out, sum[:]...)
	}
	return out[:n]
}

// prePadLength reports the framed length before bucket padding, derived from
// the frozen layout via the package's own SealedRegion so the test does not
// restate offsets.
func prePadLength(t *testing.T, b []byte) int {
	t.Helper()
	start, end, err := blob.SealedRegion(b)
	if err != nil {
		t.Fatalf("sealed region: %v", err)
	}
	payloadLen := int(binary.BigEndian.Uint32(b[start : start+4]))
	if start+4+payloadLen > end {
		t.Fatalf("payload length %d runs past the sealed region", payloadLen)
	}
	return start + 4 + payloadLen + blob.TagSize
}

// bucketEdgePlaintext finds a plaintext whose framed length lands exactly one
// byte under bucket bucketIdx, i.e. a blob with exactly one padding byte.
//
// It is the fixture that catches an off-by-one anywhere in the offset math:
// an ordinary fixture has hundreds of bytes of slack, so a reader that
// miscounted the header by one would still find the payload.
//
// gzip of incompressible input runs about len+18, and the framing overhead is
// ~83, so the answer is near bucket-101; the window is wide enough to absorb
// deflate's block accounting without scanning the whole bucket.
func bucketEdgePlaintext(t *testing.T, e blob.Envelope, bucketIdx int) []byte {
	t.Helper()
	bucket := blob.Buckets[bucketIdx]
	target := bucket - 1
	var sealer blob.PlaintextSealer
	for n := bucket - 200; n < bucket; n++ {
		if n < 1 {
			continue
		}
		pt := incompressibleBytes(n)
		s, err := sealer.Seal(e, pt)
		if err != nil {
			continue
		}
		if s.SizeBucket < bucket {
			continue // still fits a smaller rung
		}
		if s.SizeBucket > bucket {
			break // overshot this rung entirely
		}
		if prePadLength(t, s.Bytes) == target {
			return pt
		}
	}
	t.Fatalf("no plaintext frames to exactly %d bytes (bucket %d)", target, bucket)
	return nil
}

// escapeTrapOps is an op whose payload holds every character the two encoders
// treat differently, in the Go->TypeScript direction. Go's encoding/json escapes
// <, >, & and U+2028/U+2029 as \uXXXX; JSON.stringify emits them literally. The
// TypeScript side has a mirror fixture; without this one the asymmetry was only
// ever exercised in the direction where Go is the READER.
func escapeTrapOps() []Op {
	parent := int64(1)
	return []Op{{
		V:             SchemaVersion,
		Type:          OpTxnEdited,
		OpID:          "01J000000000000000000000G1",
		AuthoredAt:    time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
		Entity:        &EntityRef{Kind: "txn", ID: "T1"},
		ParentVersion: &parent,
		Payload: json.RawMessage(`{"merchant_raw":"كارفور",` +
			`"note":"Smith & Sons <flagged> \u2028 second line \u2029 end",` +
			`"amount_minor":"25000"}`),
	}}
}

// TestWriteConformanceFixtures regenerates the committed fixtures. It is opt-in
// (see writeFixturesEnv) because a golden file the test suite rewrites on every
// run is not a golden file.
//
//	LEDGER_WRITE_CONFORMANCE=1 go test ./internal/v2/oplog/ -run TestWriteConformanceFixtures -v
func TestWriteConformanceFixtures(t *testing.T) {
	if os.Getenv(writeFixturesEnv) != "1" {
		t.Skipf("set %s=1 to regenerate conformance/blob and conformance/op", writeFixturesEnv)
	}

	blobDir := filepath.Join(conformanceDir(), "blob")
	opDir := filepath.Join(conformanceDir(), "op")
	for _, d := range []string{blobDir, opDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}

	ops, err := EncodeBlob(goldenOps())
	if err != nil {
		t.Fatal(err)
	}
	raw, err := EncodeRawBody(goldenRawBody())
	if err != nil {
		t.Fatal(err)
	}
	checkpoint, err := EncodeCheckpointPayload(goldenCheckpointHeads())
	if err != nil {
		t.Fatal(err)
	}

	edgeEnv := blob.Envelope{UserID: conformanceUser, Stream: blob.StreamHot, WriterID: "dev-a", WriterCounter: 8}
	bigEdgeEnv := blob.Envelope{UserID: conformanceUser, Stream: blob.StreamHot, WriterID: "dev-a", WriterCounter: 12}
	type spec struct {
		file      string
		note      string
		kind      string
		env       blob.Envelope
		plaintext []byte
	}
	specs := []spec{
		{
			file:      "hot-dev-a-7.bin",
			note:      "a hot op blob: the golden op JSON of TestGoldenOpBytes, sealed at (dev-a, hot, 7)",
			kind:      KindOps,
			env:       blob.Envelope{UserID: conformanceUser, Stream: blob.StreamHot, WriterID: "dev-a", WriterCounter: 7},
			plaintext: ops,
		},
		{
			file:      "cold-ingest-3.bin",
			note:      "a cold raw-body blob: invariant I16 says this stream never carries ops",
			kind:      KindRawBody,
			env:       blob.Envelope{UserID: conformanceUser, Stream: blob.StreamCold, WriterID: IngestWriterID, WriterCounter: 3},
			plaintext: raw,
		},
		{
			file:      "hot-dev-a-8-bucket-edge.bin",
			note:      "a blob framed to exactly one byte under the 1 KiB bucket: one padding byte, so an off-by-one in any offset is fatal",
			kind:      KindRawBody,
			env:       edgeEnv,
			plaintext: nil, // filled in below; it depends on the envelope's AAD length
		},
		{
			file:      "hot-dev-a-11-escapes.bin",
			note:      "an op payload holding every character Go escapes and JSON.stringify does not, plus non-ASCII: the Go->TypeScript direction of that asymmetry",
			kind:      KindOps,
			env:       blob.Envelope{UserID: conformanceUser, Stream: blob.StreamHot, WriterID: "dev-a", WriterCounter: 11},
			plaintext: mustEncodeBlob(t, escapeTrapOps()),
		},
		{
			file:      "hot-dev-a-12-bucket-edge-4k.bin",
			note:      "one byte under rung 1 of the ladder: without it every fixture sits in bucket 0 and no blob crosses the executor boundary on a higher rung",
			kind:      "",
			env:       bigEdgeEnv,
			plaintext: nil, // filled in below
		},
	}
	// Both edge fixtures are raw bytes rather than records, so they carry no
	// kind, and their plaintexts depend on their envelope's AAD length.
	specs[2].plaintext = bucketEdgePlaintext(t, edgeEnv, 0)
	specs[2].kind = ""
	specs[4].plaintext = bucketEdgePlaintext(t, bigEdgeEnv, 1)

	var sealer blob.PlaintextSealer
	man := blobManifest{
		Note: "Sealed by internal/v2/oplog TestWriteConformanceFixtures. " +
			"Regenerate with LEDGER_WRITE_CONFORMANCE=1; do not hand-edit. " +
			"Both executors open these bytes; the framing is frozen (see internal/v2/blob).",
		Buckets:     blob.Buckets,
		NonceSize:   blob.NonceSize,
		TagSize:     blob.TagSize,
		ZeroHashHex: hex.EncodeToString(blob.ZeroHash[:]),
	}
	for _, s := range specs {
		sealed, err := sealer.Seal(s.env, s.plaintext)
		if err != nil {
			t.Fatalf("%s: %v", s.file, err)
		}
		if err := os.WriteFile(filepath.Join(blobDir, s.file), sealed.Bytes, 0o644); err != nil {
			t.Fatal(err)
		}
		man.Fixtures = append(man.Fixtures, blobFixture{
			File: s.file,
			Note: s.note,
			Kind: s.kind,
			Envelope: fixtureEnvelope{
				UserID:        s.env.UserID.String(),
				Stream:        s.env.Stream,
				WriterID:      s.env.WriterID,
				WriterCounter: strconv.FormatInt(s.env.WriterCounter, 10),
			},
			ExpectAAD:             string(s.env.AAD()),
			ExpectBucket:          sealed.SizeBucket,
			ExpectPlaintextBase64: base64.StdEncoding.EncodeToString(s.plaintext),
			ExpectPrePadLength:    prePadLength(t, sealed.Bytes),
		})
	}

	// The chain vector, generated rather than transcribed. chain_test.go pins
	// the same two hashes against literals, so the two must agree here.
	prev := blob.ZeroHash
	for _, step := range []struct {
		fill byte
		n    int
	}{{0xab, 1024}, {0xcd, 1024}} {
		body := bytes.Repeat([]byte{step.fill}, step.n)
		h := blob.Hash(prev, blob.Sealed{Bytes: body, SizeBucket: step.n})
		man.ChainSteps = append(man.ChainSteps, chainStep{
			FillByte:   hex.EncodeToString([]byte{step.fill}),
			Length:     step.n,
			ExpectHash: hex.EncodeToString(h[:]),
		})
		prev = h
	}
	writeJSONFixture(t, filepath.Join(blobDir, "manifest.json"), man)

	opMan := opManifest{
		Note: "Encoded by internal/v2/oplog TestWriteConformanceFixtures. " +
			"parent_version is a raw JSON NUMBER on the wire and a decimal string in this manifest; " +
			"money and counters are decimal strings on the wire. " +
			"authored_at_cases pin PARSED INSTANTS: Go's RFC3339Nano trims trailing " +
			"zeros where JavaScript's toISOString pads to three digits, so the two encoders are " +
			"byte-different and instant-identical. expect_canonical_wire is the one exception — it is " +
			"the string THIS executor writes, and the TypeScript side asserts it can READ it, which " +
			"is how a canonical form outside the shared four-digit-year grammar (years 10000 and -1 " +
			"are both reachable from a wire-legal input) becomes visible to the suite at all.",
		SchemaVersion:              SchemaVersion,
		GoldenOpsBase64:            base64.StdEncoding.EncodeToString(ops),
		GoldenRawBodyBase64:        base64.StdEncoding.EncodeToString(raw),
		GoldenCheckpointBase64:     base64.StdEncoding.EncodeToString(checkpoint),
		DuplicateDispositionBase64: base64.StdEncoding.EncodeToString(mustEncodeBlob(t, duplicateDispositionOps())),
		VerifiedOriginBase64:       base64.StdEncoding.EncodeToString(mustEncodeBlob(t, verifiedOriginOps())),
		DuplicateDispositionInvalidPayloads: []json.RawMessage{
			json.RawMessage(`{}`), json.RawMessage(`{"other_txn_id":"T0"}`),
			json.RawMessage(`{"other_txn_id":"","disposition":"same"}`), json.RawMessage(`{"other_txn_id":7,"disposition":"same"}`),
			json.RawMessage(`{"other_txn_id":"T0","disposition":"merge"}`), json.RawMessage(`{"other_txn_id":"T0","disposition":7}`),
			json.RawMessage(`null`), json.RawMessage(`[]`),
		},
	}
	for _, ty := range Types {
		opMan.Types = append(opMan.Types, string(ty))
		if ty.ParentFree() {
			opMan.ParentFree = append(opMan.ParentFree, string(ty))
		}
	}
	decoded, err := DecodeBlob(ops)
	if err != nil {
		t.Fatal(err)
	}
	for _, o := range decoded {
		e := opExpect{
			Type:             string(o.Type),
			OpID:             o.OpID,
			AuthoredAtUnixMs: strconv.FormatInt(o.AuthoredAt.UnixMilli(), 10),
			HasEntity:        o.Entity != nil,
			IngestID:         o.IngestID,
		}
		if o.ParentVersion != nil {
			s := strconv.FormatInt(*o.ParentVersion, 10)
			e.ParentVersion = &s
		}
		opMan.ExpectOps = append(opMan.ExpectOps, e)
	}
	// The sub-millisecond, offset and leap-year cases, decoded by this build.
	// TestDecodeTruncatesAuthoredAtToMilliseconds asserts the same rule against
	// Go literals; here the answers are handed to the other executor.
	for _, wire := range timeAcceptCases {
		got, err := DecodeBlob(timeProbeBlob(wire))
		if err != nil {
			t.Fatalf("%s: %v", wire, err)
		}
		canonical, err := CanonicalWireTime(got[0].AuthoredAt)
		if err != nil {
			t.Fatalf("%s: an ACCEPTED timestamp must have a canonical form: %v", wire, err)
		}
		opMan.AuthoredAtCases = append(opMan.AuthoredAtCases, timeCase{
			Wire:                wire,
			ExpectUnixMs:        strconv.FormatInt(got[0].AuthoredAt.UnixMilli(), 10),
			ExpectCanonicalWire: canonical,
		})
	}
	// The parent_version asymmetry, encoded by this executor so the other can
	// check it refuses exactly these bytes.
	overflow := int64(1)<<53 + 1
	overflowBlob, err := EncodeBlob([]Op{{
		V:             SchemaVersion,
		Type:          OpTxnCategorized,
		OpID:          "01J000000000000000000000P1",
		AuthoredAt:    time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
		Entity:        &EntityRef{Kind: "txn", ID: "T1"},
		ParentVersion: &overflow,
		Payload:       json.RawMessage(`{"category":"groceries"}`),
	}})
	if err != nil {
		t.Fatal(err)
	}
	opMan.ParentVersionOverflowBase64 = base64.StdEncoding.EncodeToString(overflowBlob)
	opMan.ParentVersionOverflow = strconv.FormatInt(overflow, 10)

	for _, wire := range timeRejectCases {
		if _, err := DecodeBlob(timeProbeBlob(wire)); err == nil {
			t.Fatalf("authored_at %q must be refused before it can be written as a reject case", wire)
		}
		opMan.AuthoredAtRejects = append(opMan.AuthoredAtRejects, wire)
	}
	writeJSONFixture(t, filepath.Join(opDir, "manifest.json"), opMan)
}

// timeProbeBlob is a minimal one-op blob carrying an arbitrary authored_at
// string, used to ask each executor what instant it reads out of it.
func timeProbeBlob(wire string) []byte {
	return []byte(`{"v":1,"kind":"ops","ops":[{"v":1,"type":"rate_set",` +
		`"op_id":"01J000000000000000000000R1","authored_at":"` + wire + `",` +
		`"parent_version":null,"payload":{}}]}`)
}

func writeJSONFixture(t *testing.T, path string, v any) {
	t.Helper()
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, append(b, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
}

// ---------------------------------------------------------------------------
// The always-on halves: this build must still agree with what it wrote, and
// with what the other executor writes.
// ---------------------------------------------------------------------------

func readBlobManifest(t *testing.T, dir string) blobManifest {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, "manifest.json"))
	if err != nil {
		// Not a skip. A missing fixture set means the cross-executor gate is not
		// running, and a gate that silently disables itself is worse than no gate.
		t.Fatalf("conformance manifest is missing (%v); regenerate with %s=1", err, writeFixturesEnv)
	}
	var man blobManifest
	if err := json.Unmarshal(b, &man); err != nil {
		t.Fatal(err)
	}
	if len(man.Fixtures) == 0 {
		t.Fatal("conformance manifest lists no fixtures")
	}
	return man
}

// checkFixtures opens every fixture in dir and asserts it still yields the
// pinned plaintext at the pinned position. It is shared by the Go-authored and
// the TypeScript-authored sets: the assertion is the same in both directions,
// which is the point of a frozen format.
func checkFixtures(t *testing.T, dir string) {
	t.Helper()
	man := readBlobManifest(t, dir)
	var sealer blob.PlaintextSealer
	for _, f := range man.Fixtures {
		t.Run(f.File, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(dir, f.File))
			if err != nil {
				t.Fatal(err)
			}
			if len(raw) != f.ExpectBucket {
				t.Fatalf("blob is %d bytes, manifest says bucket %d", len(raw), f.ExpectBucket)
			}
			env := f.Envelope.blobEnvelope(t)
			if got := string(env.AAD()); got != f.ExpectAAD {
				t.Fatalf("AAD is %q, manifest says %q", got, f.ExpectAAD)
			}
			if embedded, err := blob.EmbeddedAAD(raw); err != nil {
				t.Fatalf("embedded AAD: %v", err)
			} else if string(embedded) != f.ExpectAAD {
				t.Fatalf("embedded AAD is %q, manifest says %q", embedded, f.ExpectAAD)
			}
			if got := prePadLength(t, raw); got != f.ExpectPrePadLength {
				t.Fatalf("framed length before padding is %d, manifest says %d", got, f.ExpectPrePadLength)
			}

			plaintext, err := sealer.Open(env, blob.Sealed{Bytes: raw, SizeBucket: len(raw)})
			if err != nil {
				t.Fatalf("open: %v", err)
			}
			want, err := base64.StdEncoding.DecodeString(f.ExpectPlaintextBase64)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(plaintext, want) {
				t.Fatalf("plaintext differs from the manifest:\n got %q\nwant %q", plaintext, want)
			}

			// Moving the blob one position along must be refused. Without this
			// the whole fixture set would pass against an Open that ignored the
			// AAD entirely.
			moved := env
			moved.WriterCounter++
			if _, err := sealer.Open(moved, blob.Sealed{Bytes: raw, SizeBucket: len(raw)}); err == nil {
				t.Fatal("opening the fixture at the next counter must fail")
			}

			switch f.Kind {
			case KindOps:
				if _, err := DecodeBlob(plaintext); err != nil {
					t.Fatalf("decode ops: %v", err)
				}
				if _, err := DecodeRawBody(plaintext); err == nil {
					t.Fatal("an op blob must not decode as a raw body (invariant I16)")
				}
			case KindRawBody:
				rb, err := DecodeRawBody(plaintext)
				if err != nil {
					t.Fatalf("decode raw body: %v", err)
				}
				// The PAYLOAD is decoded, not just the record around it.
				// DecodeRawBody used to hand back RawBase64 as an unexamined
				// string, and this check only called DecodeRawBody — so the cold
				// record's actual content never crossed the executor boundary at
				// all, and a TypeScript encoder emitting unpadded base64url
				// passed this gate green.
				raw, err := base64.StdEncoding.DecodeString(rb.RawBase64)
				if err != nil {
					t.Fatalf("raw_base64 does not decode: %v", err)
				}
				if len(raw) == 0 {
					t.Fatal("cold fixtures must carry a non-empty body, or this check proves nothing")
				}
				if got := base64.StdEncoding.EncodeToString(raw); got != rb.RawBase64 {
					t.Fatalf("raw_base64 is not canonical standard base64:\n got %s\nwant %s", rb.RawBase64, got)
				}
				if _, err := DecodeBlob(plaintext); err == nil {
					t.Fatal("a raw-body blob must not decode as ops (invariant I16)")
				}
			}
		})
	}
}

// TestConformanceFixturesAreWhatThisBuildProduces is the Go half of the
// dual-executor gate: the committed bytes must still open, at the same
// positions, to the same plaintexts, under this build.
func TestConformanceFixturesAreWhatThisBuildProduces(t *testing.T) {
	dir := filepath.Join(conformanceDir(), "blob")
	checkFixtures(t, dir)

	man := readBlobManifest(t, dir)
	// The layout constants travel in the manifest so the TypeScript port has one
	// source for them rather than a hand-copied ladder.
	if len(man.Buckets) != len(blob.Buckets) {
		t.Fatalf("manifest lists %d buckets, this build has %d", len(man.Buckets), len(blob.Buckets))
	}
	for i, b := range blob.Buckets {
		if man.Buckets[i] != b {
			t.Fatalf("bucket %d is %d, manifest says %d", i, b, man.Buckets[i])
		}
	}
	if man.NonceSize != blob.NonceSize || man.TagSize != blob.TagSize {
		t.Fatalf("reserved slot sizes moved: manifest has nonce %d tag %d, build has %d/%d",
			man.NonceSize, man.TagSize, blob.NonceSize, blob.TagSize)
	}
	if man.ZeroHashHex != hex.EncodeToString(blob.ZeroHash[:]) {
		t.Fatalf("chain genesis moved: manifest %s", man.ZeroHashHex)
	}

	prev := blob.ZeroHash
	for i, step := range man.ChainSteps {
		fill, err := hex.DecodeString(step.FillByte)
		if err != nil || len(fill) != 1 {
			t.Fatalf("chain step %d has fill byte %q", i, step.FillByte)
		}
		body := bytes.Repeat(fill, step.Length)
		h := blob.Hash(prev, blob.Sealed{Bytes: body, SizeBucket: step.Length})
		if got := hex.EncodeToString(h[:]); got != step.ExpectHash {
			t.Fatalf("chain step %d hashes to %s, manifest says %s", i, got, step.ExpectHash)
		}
		prev = h
	}
	if len(man.ChainSteps) == 0 {
		t.Fatal("the manifest carries no chain vector")
	}
}

// readOpManifest opens the committed op manifest. Shared by the two tests that
// read it, so a second reader cannot drift into a second copy of the "missing
// fixture" policy — a missing manifest is a FATAL, never a skip, because a gate
// that silently disables itself is worse than no gate.
func readOpManifest(t *testing.T) opManifest {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(conformanceDir(), "op", "manifest.json"))
	if err != nil {
		t.Fatalf("op manifest is missing (%v); regenerate with %s=1", err, writeFixturesEnv)
	}
	var man opManifest
	if err := json.Unmarshal(b, &man); err != nil {
		t.Fatal(err)
	}
	return man
}

// TestOpConformanceManifestMatchesThisBuild does the same for the op wire
// model: the golden bytes must still encode and decode identically here.
func TestOpConformanceManifestMatchesThisBuild(t *testing.T) {
	man := readOpManifest(t)
	if man.SchemaVersion != SchemaVersion {
		t.Fatalf("manifest is for schema v%d, this build is v%d", man.SchemaVersion, SchemaVersion)
	}
	duplicateBytes, err := base64.StdEncoding.DecodeString(man.DuplicateDispositionBase64)
	if err != nil {
		t.Fatal(err)
	}
	duplicateOps, err := DecodeBlob(duplicateBytes)
	if err != nil {
		t.Fatal(err)
	}
	if len(duplicateOps) != 1 || duplicateOps[0].Type != OpTxnDuplicateDisposition {
		t.Fatalf("duplicate disposition fixture decoded as %#v", duplicateOps)
	}
	baseInvalid := duplicateDispositionOps()[0]
	for _, payload := range man.DuplicateDispositionInvalidPayloads {
		bad := baseInvalid
		bad.Payload = payload
		if err := bad.Validate(); err == nil {
			t.Fatalf("Go accepted shared invalid duplicate-disposition payload %s", payload)
		}
	}
	if len(man.Types) != len(Types) {
		t.Fatalf("manifest lists %d op types, this build has %d", len(man.Types), len(Types))
	}
	for i, ty := range Types {
		if man.Types[i] != string(ty) {
			t.Fatalf("op type %d is %q, manifest says %q", i, ty, man.Types[i])
		}
	}
	for _, ty := range man.ParentFree {
		if !OpType(ty).ParentFree() {
			t.Fatalf("manifest calls %q parent-free and this build does not", ty)
		}
	}

	ops, err := EncodeBlob(goldenOps())
	if err != nil {
		t.Fatal(err)
	}
	if got := base64.StdEncoding.EncodeToString(ops); got != man.GoldenOpsBase64 {
		want, _ := base64.StdEncoding.DecodeString(man.GoldenOpsBase64)
		t.Fatalf("op blob encoding changed:\n got %s\nwant %s", ops, want)
	}
	raw, err := EncodeRawBody(goldenRawBody())
	if err != nil {
		t.Fatal(err)
	}
	if got := base64.StdEncoding.EncodeToString(raw); got != man.GoldenRawBodyBase64 {
		t.Fatalf("raw body encoding changed: %s", raw)
	}
	cp, err := EncodeCheckpointPayload(goldenCheckpointHeads())
	if err != nil {
		t.Fatal(err)
	}
	if got := base64.StdEncoding.EncodeToString(cp); got != man.GoldenCheckpointBase64 {
		t.Fatalf("checkpoint payload encoding changed: %s", cp)
	}

	decoded, err := DecodeBlob(ops)
	if err != nil {
		t.Fatal(err)
	}
	if len(decoded) != len(man.ExpectOps) {
		t.Fatalf("golden blob has %d ops, manifest expects %d", len(decoded), len(man.ExpectOps))
	}
	for i, want := range man.ExpectOps {
		got := decoded[i]
		if string(got.Type) != want.Type || got.OpID != want.OpID {
			t.Fatalf("op %d is %s/%s, manifest says %s/%s", i, got.Type, got.OpID, want.Type, want.OpID)
		}
		if ms := strconv.FormatInt(got.AuthoredAt.UnixMilli(), 10); ms != want.AuthoredAtUnixMs {
			t.Fatalf("op %d authored at %s ms, manifest says %s", i, ms, want.AuthoredAtUnixMs)
		}
		if (got.Entity != nil) != want.HasEntity {
			t.Fatalf("op %d entity presence disagrees with the manifest", i)
		}
		if got.IngestID != want.IngestID {
			t.Fatalf("op %d ingest_id is %q, manifest says %q", i, got.IngestID, want.IngestID)
		}
		switch {
		case got.ParentVersion == nil && want.ParentVersion != nil:
			t.Fatalf("op %d has no parent_version, manifest says %s", i, *want.ParentVersion)
		case got.ParentVersion != nil && want.ParentVersion == nil:
			t.Fatalf("op %d has parent_version %d, manifest says null", i, *got.ParentVersion)
		case got.ParentVersion != nil && strconv.FormatInt(*got.ParentVersion, 10) != *want.ParentVersion:
			t.Fatalf("op %d parent_version is %d, manifest says %s", i, *got.ParentVersion, *want.ParentVersion)
		}
	}

	// Counted against this build's own list, the way the reject side already is.
	// Without it a case can be DELETED from the fixture and both executors stay
	// green — the accept side had exactly that hole, and a mutation run walked
	// through it by dropping the year-9999 case.
	if len(man.AuthoredAtCases) != len(timeAcceptCases) {
		t.Fatalf("the manifest lists %d authored_at cases, this build has %d", len(man.AuthoredAtCases), len(timeAcceptCases))
	}
	// And the boundary ones named, for the reason the parent-free set is: the
	// list is generated, so deleting an entry and regenerating moves both
	// executors together.
	haveCase := make(map[string]bool, len(man.AuthoredAtCases))
	for _, c := range man.AuthoredAtCases {
		haveCase[c.Wire] = true
	}
	for _, must := range []string{
		"0000-01-01T00:00:00Z",
		"9999-12-31T23:59:59.999Z",
		"0000-02-29T00:00:00Z",
		"2026-06-05T10:00:00-23:59",
	} {
		if !haveCase[must] {
			t.Fatalf("the manifest no longer publishes the boundary accept case %q", must)
		}
	}
	for _, c := range man.AuthoredAtCases {
		got, err := DecodeBlob(timeProbeBlob(c.Wire))
		if err != nil {
			t.Fatalf("%s: %v", c.Wire, err)
		}
		if ms := strconv.FormatInt(got[0].AuthoredAt.UnixMilli(), 10); ms != c.ExpectUnixMs {
			t.Fatalf("%s decodes to %s ms, manifest says %s", c.Wire, ms, c.ExpectUnixMs)
		}
		// Go's canonical SPELLING, pinned. The TypeScript side reads this exact
		// string; a change to how this executor renders a timestamp fails here
		// before it reaches a device that cannot parse it.
		canonical, err := CanonicalWireTime(got[0].AuthoredAt)
		if err != nil {
			t.Fatalf("%s: accepted but has no canonical form: %v", c.Wire, err)
		}
		if canonical != c.ExpectCanonicalWire {
			t.Fatalf("%s canonicalises to %q, manifest says %q", c.Wire, canonical, c.ExpectCanonicalWire)
		}
	}
	// Go reads the overflow blob exactly; TypeScript must refuse it. Asserting
	// the Go half here is what makes the TypeScript refusal meaningful rather
	// than a test of a string nobody produces.
	overflowBlob, err := base64.StdEncoding.DecodeString(man.ParentVersionOverflowBase64)
	if err != nil {
		t.Fatal(err)
	}
	overflowOps, err := DecodeBlob(overflowBlob)
	if err != nil {
		t.Fatalf("the parent_version overflow blob must decode HERE: %v", err)
	}
	if len(overflowOps) != 1 || overflowOps[0].ParentVersion == nil {
		t.Fatal("the parent_version overflow blob lost its parent_version")
	}
	if got := strconv.FormatInt(*overflowOps[0].ParentVersion, 10); got != man.ParentVersionOverflow {
		t.Fatalf("parent_version decoded as %s, manifest says %s", got, man.ParentVersionOverflow)
	}

	// Named explicitly as well as compared, for the reason the parent-free set
	// is: everything above is GENERATED from timeRejectCases, so deleting an
	// entry and regenerating would take both executors green together. These
	// six are the expanded-year contract and cannot leave the manifest quietly.
	for _, must := range []string{
		"9999-12-31T23:59:59-23:59",
		"0000-01-01T00:00:00+00:01",
		"+010000-01-01T23:58:59.000Z",
		"10000-01-01T23:58:59Z",
		"-0001-12-31T23:59:00Z",
		"2026-06-05T10:00:00-24:00",
	} {
		if !slices.Contains(man.AuthoredAtRejects, must) {
			t.Fatalf("the manifest no longer promises %q is refused; the TypeScript executor reads that list", must)
		}
	}
	if len(man.AuthoredAtRejects) != len(timeRejectCases) {
		t.Fatalf("the manifest lists %d reject cases, this build has %d", len(man.AuthoredAtRejects), len(timeRejectCases))
	}
	for _, wire := range man.AuthoredAtRejects {
		if _, err := DecodeBlob(timeProbeBlob(wire)); err == nil {
			t.Fatalf("authored_at %q must be refused: the manifest promises the TypeScript executor refuses it", wire)
		}
	}
}

// TestCanonicalTimeIsClosedOverTheWireGrammar states the property whose absence
// was the defect, as a property rather than as a list of blessed strings.
//
// Canonicalisation is a function from wire timestamps to wire timestamps. If it
// can produce a value outside its own input grammar, then "both executors read
// the same instant" says nothing about the value they STORE — and the two
// languages spell exactly that overflow differently. The suite could not see it
// because every timestamp assertion in this file compared parsed instants, and
// the divergence is in a string neither side could parse.
//
// Two claims, over the same accept set the manifest publishes:
//
//  1. Closure: the canonical form of an accepted timestamp is itself accepted,
//     to the same instant. This is what makes decode∘canonical = canonical.
//  2. Idempotence: canonicalising twice changes nothing, which is what lets
//     DecodeBlob canonicalise a value EncodeBlob already canonicalised.
//
// Note there is deliberately NO `rfc3339Shape.MatchString(canonical)` assertion
// in here. parseWireTime's first statement is that same regex, so such a check
// could never fail while the round trip below passes — a check true by
// construction, which is the exact defect class this whole task is about. A
// mutation run caught it sitting there doing nothing; it was deleted rather than
// dressed up.
func TestCanonicalTimeIsClosedOverTheWireGrammar(t *testing.T) {
	// Cross-read against the published fixture rather than only against this
	// build's inputs: the canonical STRING is the thing the other executor
	// consumes, so the property and the golden are stated over the same values.
	published := map[string]string{}
	for _, c := range readOpManifest(t).AuthoredAtCases {
		published[c.Wire] = c.ExpectCanonicalWire
	}

	for _, wire := range timeAcceptCases {
		parsed, err := parseWireTime(wire)
		if err != nil {
			t.Errorf("parseWireTime(%q): %v", wire, err)
			continue
		}
		canonical, err := CanonicalWireTime(parsed)
		if err != nil {
			t.Errorf("%q is accepted but has no canonical form: %v", wire, err)
			continue
		}
		if want, ok := published[wire]; !ok {
			t.Errorf("%q is an accept case this build tests and the manifest does not publish", wire)
		} else if want != canonical {
			t.Errorf("%q canonicalises to %q, the manifest publishes %q to the other executor", wire, canonical, want)
		}
		reparsed, err := parseWireTime(canonical)
		if err != nil {
			t.Errorf("%q canonicalises to %q, which will not parse back: %v", wire, canonical, err)
			continue
		}
		if want := parsed.UTC().Truncate(time.Millisecond); !reparsed.Equal(want) {
			t.Errorf("%q round-trips to %v, want %v", wire, reparsed.UTC(), want)
		}
		again, err := CanonicalWireTime(reparsed)
		if err != nil || again != canonical {
			t.Errorf("canonicalising %q twice gives %q (%v), want %q", wire, again, err, canonical)
		}
	}
}

// TestTheExpandedYearRangeIsRefusedByBothExecutors is the regression test for
// the divergence itself, written as the two reachable boundary values rather
// than as a year check, because a year check is what both executors were
// missing and would be the same assumption twice.
//
// Reachability is the point: these are not malformed strings. Every rule that
// existed accepts them — four digits of year, a real calendar date, an offset
// inside ±23:59 — and one of them is the value Task 7 proved could strand a
// device (client/src/replay: the canonical form was stored, re-read, and threw
// out of the fold). A bank will not send year 10000; a hostile or broken Date
// header can, and the wire cannot say so.
func TestTheExpandedYearRangeIsRefusedByBothExecutors(t *testing.T) {
	for _, tc := range []struct {
		wire     string
		goSpells string // what this executor renders it as, measured
		jsSpells string // what toISOString renders it as, measured
	}{
		{"9999-12-31T23:59:59-23:59", "10000-01-01T23:58:59Z", "+010000-01-01T23:58:59.000Z"},
		{"0000-01-01T00:00:00+00:01", "-0001-12-31T23:59:00Z", "-000001-12-31T23:59:00.000Z"},
	} {
		// The spellings really do differ, and really are unreadable here. If a
		// Go release ever made Format agree with toISOString this would fail and
		// say so, rather than the contract quietly changing shape.
		loose, err := time.Parse(time.RFC3339, tc.wire)
		if err != nil {
			t.Fatalf("%q must still parse under the stock layout, or this test proves nothing: %v", tc.wire, err)
		}
		if got := loose.UTC().Truncate(time.Millisecond).Format(time.RFC3339Nano); got != tc.goSpells {
			t.Errorf("this executor now spells %q as %q, not %q", tc.wire, got, tc.goSpells)
		}
		if tc.goSpells == tc.jsSpells {
			t.Errorf("the two spellings for %q are no longer different", tc.wire)
		}
		if rfc3339Shape.MatchString(tc.goSpells) || rfc3339Shape.MatchString(tc.jsSpells) {
			t.Errorf("an expanded-year spelling for %q now satisfies the wire grammar", tc.wire)
		}

		// And the value is refused, in every direction a timestamp enters.
		if _, err := parseWireTime(tc.wire); err == nil {
			t.Errorf("parseWireTime(%q) must be refused: its canonical form is not a wire timestamp", tc.wire)
		}
		if _, err := DecodeBlob(timeProbeBlob(tc.wire)); err == nil {
			t.Errorf("an op carrying authored_at %q must not decode", tc.wire)
		} else if errors.Is(err, ErrUnknownNewerVersion) {
			t.Errorf("authored_at %q must be a set-aside, never the sync hard stop", tc.wire)
		}
		rawBody := []byte(`{"v":1,"kind":"raw_body","ingest_id":"` + strings.Repeat("a", 64) +
			`","received_at":"` + tc.wire + `","raw_base64":"aGk="}`)
		if _, err := DecodeRawBody(rawBody); err == nil {
			t.Errorf("a cold record with received_at %q must not decode", tc.wire)
		}
		// Op.Validate in its own right, not only through EncodeBlob. Validate is
		// EXPORTED and documented as "the structural rules replay depends on",
		// so a caller holding a hand-built op must be told there; EncodeBlob's
		// own check would otherwise make this one look redundant, which is how a
		// mutation run got the Validate guard deleted with every test green.
		if err := (Op{
			V: SchemaVersion, Type: OpRateSet, OpID: "01J000000000000000000000R1",
			AuthoredAt: loose, Payload: json.RawMessage(`{}`),
		}).Validate(); err == nil {
			t.Errorf("Op.Validate must refuse authored_at %q on its own", tc.wire)
		} else if !strings.Contains(err.Error(), "authored_at") {
			t.Errorf("Op.Validate's refusal of %q does not name the field: %v", tc.wire, err)
		}
		// The ENCODE side too: a writer whose clock is out there is told which
		// field and which op, instead of getting encoding/json's message about a
		// type it never named.
		if _, err := EncodeBlob([]Op{{
			V: SchemaVersion, Type: OpRateSet, OpID: "01J000000000000000000000R1",
			AuthoredAt: loose, Payload: json.RawMessage(`{}`),
		}}); err == nil {
			t.Errorf("EncodeBlob must refuse authored_at %q", tc.wire)
		} else if !strings.Contains(err.Error(), "authored_at") {
			t.Errorf("EncodeBlob's refusal of %q does not name the field: %v", tc.wire, err)
		}
		if _, err := EncodeRawBody(RawBody{
			IngestID: strings.Repeat("a", 64), ReceivedAt: loose, RawBase64: "aGk=",
		}); err == nil {
			t.Errorf("EncodeRawBody must refuse received_at %q", tc.wire)
		}
	}

	// The legal neighbours still pass, so the refusal is the range and not the
	// millennium either side of it.
	for _, ok := range []string{"9999-12-31T23:59:59.999Z", "0000-01-01T00:00:00Z", "0000-02-29T00:00:00Z"} {
		if _, err := parseWireTime(ok); err != nil {
			t.Errorf("parseWireTime(%q) must still be accepted: %v", ok, err)
		}
	}
}

// TestTypeScriptSealedBlobsOpenInGo closes the direction a Go-authored fixture
// set cannot: a TypeScript port that reads Go's bytes perfectly and WRITES
// subtly wrong ones passes every other test in this file, and would then be
// discovered by the server rejecting a device's uploads — or worse, by the
// server accepting them and no other device being able to open them.
//
// The fixtures are produced by `cd client && bun run gen-fixtures` and
// committed; that script also asserts the bytes it is about to write are the
// bytes the current TypeScript produces, so a stale set fails on the TS side.
func TestTypeScriptSealedBlobsOpenInGo(t *testing.T) {
	dir := filepath.Join(conformanceDir(), "ts")
	checkFixtures(t, dir)

	// And the ops inside must be the ops the TypeScript claimed to write. The
	// comparison is on values, never on bytes: Go escapes <, > and & as <
	// and friends where JSON.stringify does not, so the two encoders produce
	// different bytes for the same op — which is exactly why the ampersand
	// fixture is in the set.
	var sealer blob.PlaintextSealer
	man := readBlobManifest(t, dir)
	found := 0
	for _, f := range man.Fixtures {
		if f.Kind != KindOps {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(dir, f.File))
		if err != nil {
			t.Fatal(err)
		}
		plaintext, err := sealer.Open(f.Envelope.blobEnvelope(t), blob.Sealed{Bytes: raw, SizeBucket: len(raw)})
		if err != nil {
			t.Fatalf("%s: %v", f.File, err)
		}
		ops, err := DecodeBlob(plaintext)
		if err != nil {
			t.Fatalf("%s: %v", f.File, err)
		}
		if len(ops) == 0 {
			t.Fatalf("%s: TypeScript wrote an empty op blob", f.File)
		}
		found++

		if f.File == "ts-hot-dev-a-7.bin" {
			want := goldenOps()
			if len(ops) != len(want) {
				t.Fatalf("%s: %d ops, want %d", f.File, len(ops), len(want))
			}
			for i := range want {
				if ops[i].Type != want[i].Type || ops[i].OpID != want[i].OpID {
					t.Fatalf("%s: op %d is %s/%s, want %s/%s", f.File, i, ops[i].Type, ops[i].OpID, want[i].Type, want[i].OpID)
				}
				if !ops[i].AuthoredAt.Equal(want[i].AuthoredAt) {
					t.Fatalf("%s: op %d authored at %v, want %v — the two executors must read the same INSTANT",
						f.File, i, ops[i].AuthoredAt, want[i].AuthoredAt)
				}
				if (ops[i].ParentVersion == nil) != (want[i].ParentVersion == nil) {
					t.Fatalf("%s: op %d parent_version presence differs", f.File, i)
				}
				if ops[i].ParentVersion != nil && *ops[i].ParentVersion != *want[i].ParentVersion {
					t.Fatalf("%s: op %d parent_version is %d, want %d", f.File, i, *ops[i].ParentVersion, *want[i].ParentVersion)
				}
				if (ops[i].Entity == nil) != (want[i].Entity == nil) {
					t.Fatalf("%s: op %d entity presence differs", f.File, i)
				}
				if ops[i].Entity != nil && (ops[i].Entity.Kind != want[i].Entity.Kind || ops[i].Entity.ID != want[i].Entity.ID) {
					t.Fatalf("%s: op %d entity is %+v, want %+v", f.File, i, ops[i].Entity, want[i].Entity)
				}
				if ops[i].IngestID != want[i].IngestID {
					t.Fatalf("%s: op %d ingest_id is %q, want %q", f.File, i, ops[i].IngestID, want[i].IngestID)
				}
				var gotPayload, wantPayload any
				if err := json.Unmarshal(ops[i].Payload, &gotPayload); err != nil {
					t.Fatal(err)
				}
				if err := json.Unmarshal(want[i].Payload, &wantPayload); err != nil {
					t.Fatal(err)
				}
				if !jsonEqual(gotPayload, wantPayload) {
					t.Fatalf("%s: op %d payload is %s, want %s", f.File, i, ops[i].Payload, want[i].Payload)
				}
			}
		}

		if f.File == "ts-hot-dev-a-9-escapes.bin" {
			// The escaping fixture: Go must read back the exact strings the
			// TypeScript wrote, including the characters Go's own encoder would
			// have escaped.
			var payload struct {
				Merchant string `json:"merchant_raw"`
				Note     string `json:"note"`
			}
			if err := json.Unmarshal(ops[0].Payload, &payload); err != nil {
				t.Fatal(err)
			}
			// U+2028 is in the set on purpose: Go's encoder escapes it and
			// JSON.stringify does not, so it is the sharpest form of the
			// escaping asymmetry this fixture exists to prove is harmless.
			for _, want := range []string{"&", "<", ">", "\u2028"} {
				if !strings.Contains(payload.Note, want) {
					t.Fatalf("%s: note %q lost %q in transit", f.File, payload.Note, want)
				}
			}
			if payload.Merchant != "كارفور" {
				t.Fatalf("%s: merchant is %q, want the Arabic original", f.File, payload.Merchant)
			}
		}
	}
	if found < 2 {
		t.Fatalf("expected at least two TypeScript-authored op blobs, found %d", found)
	}
}

// jsonEqual compares two decoded JSON values structurally.
func jsonEqual(a, b any) bool {
	x, errA := json.Marshal(a)
	y, errB := json.Marshal(b)
	return errA == nil && errB == nil && bytes.Equal(x, y)
}
