package oplog

// conformance_test.go is the shared-bytes half of the dual-executor contract.
//
// Spec §3.5 mandates two independent executors — this Go one and the TypeScript
// one in client/ — and says a disagreement fails the build. Two implementations
// that only ever test themselves cannot disagree, so the agreement is made
// mechanical here: this file WRITES a set of fixtures from the Go encoders and
// then, on every run, RE-READS them and asserts this build still agrees with
// them. The TypeScript side reads exactly the same files.
//
// # Why the fixtures live here and not in package blob
//
// The plan put the fixture writer in internal/v2/blob. It cannot live there:
// oplog imports blob, so blob cannot import oplog, and a blob-package writer
// would have to carry a hand-copied literal of the op JSON — a second copy of a
// frozen wire format, which is the exact failure mode fixtures exist to prevent.
// Written here, every fixture's plaintext comes out of the real EncodeBlob and
// EncodeRawBody, and goldenOps is shared with TestGoldenOpBytes so there is one
// literal in the repository, not two.
//
// # Three directions are covered, and each catches something different
//
//  1. conformance/blob + conformance/op are written BY Go and read BY both.
//     TestConformanceFixturesAreWhatThisBuildProduces re-opens them here; the
//     TypeScript blob.test.ts/op.test.ts open the same bytes. A change to the
//     framing, the bucket ladder, the AAD field set or the op JSON breaks
//     whichever side moved.
//
//  2. conformance/ts is written BY TypeScript (client/scripts/gen-fixtures.ts)
//     and read here by TestTypeScriptSealedBlobsOpenInGo. That is the direction
//     a fixture set alone always misses: a TS port that decodes Go's bytes
//     perfectly and emits subtly wrong ones would pass every test in group 1.
//     It is also the direction the server sees, since a device uploads blobs it
//     sealed itself.
//
//  3. The parsed-instant cases in conformance/op/manifest.json pin the
//     millisecond rule (canonicalTime) as a set of (wire string, unix
//     milliseconds) pairs generated by THIS decoder. Comparing instants rather
//     than strings is deliberate: Go's RFC3339Nano trims trailing zeros where
//     JavaScript's toISOString always pads to three digits, so the two encoders
//     are byte-different and instant-identical, and only the second is claimed.
//
// # What is deliberately NOT asserted
//
// That re-sealing a fixture reproduces its stored bytes. Sealing gzips, and
// gzip output is a property of the compressor rather than of the format: a Go
// release that retunes compress/flate would fail such a check while breaking
// nothing (every stored blob still opens, because gunzip does not care which
// encoder produced the stream). The durable claim is the one asserted below —
// the committed bytes still OPEN to the pinned plaintext, in both languages.

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	"ledger/internal/v2/blob"
)

// writeFixturesEnv gates the writer. A test that rewrites its own reference on
// every run pins nothing — it would silently re-bless whatever the code now
// produces, which is the one thing a golden file exists to prevent — so writing
// is opt-in and the fixtures are committed.
const writeFixturesEnv = "LEDGER_WRITE_CONFORMANCE"

// conformanceUser is the user id every fixture is sealed for. It is the same
// value package blob's own tests use, so a fixture's AAD is readable at a glance.
var conformanceUser = uuid.MustParse("11111111-1111-1111-1111-111111111111")

// ---------------------------------------------------------------------------
// The manifest shapes. Every integer that is an int64 on the wire is a decimal
// STRING here for the same reason it is one in the op model: a JSON number
// parsed by JavaScript is a float64.
// ---------------------------------------------------------------------------

type fixtureEnvelope struct {
	UserID        string `json:"user_id"`
	Stream        string `json:"stream"`
	WriterID      string `json:"writer_id"`
	WriterCounter string `json:"writer_counter"`
}

func (e fixtureEnvelope) blobEnvelope(t *testing.T) blob.Envelope {
	t.Helper()
	id, err := uuid.Parse(e.UserID)
	if err != nil {
		t.Fatalf("fixture envelope has an unparseable user id %q: %v", e.UserID, err)
	}
	counter, err := strconv.ParseInt(e.WriterCounter, 10, 64)
	if err != nil {
		t.Fatalf("fixture envelope has an unparseable counter %q: %v", e.WriterCounter, err)
	}
	return blob.Envelope{UserID: id, Stream: e.Stream, WriterID: e.WriterID, WriterCounter: counter}
}

type blobFixture struct {
	File                  string          `json:"file"`
	Note                  string          `json:"note"`
	Kind                  string          `json:"kind"` // KindOps or KindRawBody
	Envelope              fixtureEnvelope `json:"envelope"`
	ExpectAAD             string          `json:"expect_aad"`
	ExpectBucket          int             `json:"expect_bucket"`
	ExpectPlaintextBase64 string          `json:"expect_plaintext_base64"`
	// ExpectPrePadLength is the framed length before bucket padding. It is what
	// makes the boundary fixture a boundary fixture, and it is unreadable from
	// the padded bytes without walking the framing — which is the point.
	ExpectPrePadLength int `json:"expect_pre_pad_length"`
}

type chainStep struct {
	FillByte   string `json:"fill_byte"` // one hex byte, repeated
	Length     int    `json:"length"`
	ExpectHash string `json:"expect_hash"` // hex; SHA256(prev || bytes)
}

type blobManifest struct {
	Note        string        `json:"note"`
	Buckets     []int         `json:"buckets"`
	NonceSize   int           `json:"nonce_size"`
	TagSize     int           `json:"tag_size"`
	ZeroHashHex string        `json:"zero_hash_hex"`
	ChainSteps  []chainStep   `json:"chain_steps"`
	Fixtures    []blobFixture `json:"fixtures"`
}

type opExpect struct {
	Type             string `json:"type"`
	OpID             string `json:"op_id"`
	AuthoredAtUnixMs string `json:"authored_at_unix_ms"`
	HasEntity        bool   `json:"has_entity"`
	// ParentVersion is a decimal string or null, mirroring the ambiguity the
	// wire deliberately does not have: on the wire parent_version is a raw JSON
	// NUMBER (see the note in the manifest), but a manifest that repeated that
	// choice could not express a value above 2^53 for the TypeScript reader to
	// check itself against.
	ParentVersion *string `json:"parent_version"`
	IngestID      string  `json:"ingest_id"`
}

type timeCase struct {
	Wire         string `json:"wire"`
	ExpectUnixMs string `json:"expect_unix_ms"`
}

type opManifest struct {
	Note                   string     `json:"note"`
	SchemaVersion          int        `json:"schema_version"`
	Types                  []string   `json:"types"`
	ParentFree             []string   `json:"parent_free"`
	GoldenOpsBase64        string     `json:"golden_ops_base64"`
	GoldenRawBodyBase64    string     `json:"golden_raw_body_base64"`
	GoldenCheckpointBase64 string     `json:"golden_checkpoint_base64"`
	ExpectOps              []opExpect `json:"expect_ops"`
	AuthoredAtCases        []timeCase `json:"authored_at_cases"`
	// ParentVersionOverflowBase64 is an op blob this executor accepts and the
	// TypeScript one must REFUSE: parent_version is a raw JSON number on the
	// frozen wire, so an int64 above 2^53 is expressible here and is already
	// rounded by JSON.parse before any TypeScript code sees it. The asymmetry is
	// a property of the format, not a bug in either port, so it is pinned as a
	// shared artifact rather than asserted from an inline literal on one side.
	ParentVersionOverflowBase64 string `json:"parent_version_overflow_base64"`
	// ParentVersionOverflow is that same value as a decimal string, which is the
	// only way this manifest can state it without being lossy itself.
	ParentVersionOverflow string `json:"parent_version_overflow"`
	// AuthoredAtRejects are timestamps BOTH executors must refuse. It is a
	// shared artifact rather than two independent literals on purpose: the whole
	// class of bug here is one side quietly accepting what the other refuses, and
	// two hand-maintained lists drift into exactly that.
	AuthoredAtRejects []string `json:"authored_at_rejects"`
}

// timeAcceptCases are timestamps both executors must read as the same instant.
var timeAcceptCases = []string{
	"2026-06-05T10:00:00Z",
	"2026-06-05T10:00:00.1Z",
	"2026-06-05T10:00:00.0015Z",    // truncates to 1ms, never rounds to 2
	"2026-06-05T10:00:00.0000015Z", // finer than a JS Date can hold
	"2026-06-05T14:00:00.5+04:00",
	"2026-06-05T10:00:00-00:00",
	"2026-06-05T10:00:00+23:59", // the largest offset both accept
	"2024-02-29T00:00:00Z",      // a real leap day
	"2000-02-29T00:00:00Z",      // divisible by 400
}

// timeRejectCases are timestamps both executors must refuse. Each was MEASURED
// against both runtimes; the comments name which side was the lenient one
// before this was pinned.
var timeRejectCases = []string{
	"2026-06-05T24:00:00Z",      // Date.parse rolled it to the next day
	"2026-02-30T10:00:00Z",      // Date.parse rolled it to MARCH 2nd
	"2026-02-29T00:00:00Z",      // 2026 is not a leap year
	"2026-13-05T10:00:00Z",      // month 13
	"2026-06-05T10:60:00Z",      // minute 60
	"2026-06-05T10:00:60Z",      // second 60: no leap seconds
	"2026-06-05T10:00:00+24:00", // stock Go accepted it; Date.parse refuses
	"2026-06-05T10:00:00+24:60", // stock Go read it as -25h
	"2026-06-05T10:00:00+00:60", // stock Go read it as -1h
	"2026-06-05t10:00:00z",      // Date.parse accepts lowercase; RFC3339 layout does not
	"2026-06-05 10:00:00Z",      // space separator
	"2026-06-05T10:00:00",       // no zone
	"2026-06-05T10:00:00.Z",     // empty fraction
	"0001-01-01T00:00:00Z",      // Go's zero time
	"2026-06-05",
	"June 5 2026",
	"",
}

// ---------------------------------------------------------------------------
// The fixtures themselves
// ---------------------------------------------------------------------------

func conformanceDir() string { return filepath.Join("..", "..", "..", "conformance") }

// goldenOps is the op set both TestGoldenOpBytes and the fixtures encode. One
// literal, two consumers: a change to it fails the golden byte comparison
// first, which is the readable failure.
func goldenOps() []Op {
	parent := int64(3)
	return []Op{
		// A create carrying an ingest_id: the only op shape in which that field
		// appears on the wire at all.
		{
			V:          SchemaVersion,
			Type:       OpTxnIngested,
			OpID:       "01J000000000000000000000I1",
			AuthoredAt: time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
			Entity:     &EntityRef{Kind: "txn", ID: "T1"},
			IngestID:   strings.Repeat("a", 64),
			Payload:    json.RawMessage(`{"amount_minor":"25000","currency":"AED"}`),
		},
		// A causal op with a parent version, which the wire carries as a raw
		// JSON number.
		{
			V:             SchemaVersion,
			Type:          OpTxnCategorized,
			OpID:          "01J000000000000000000000A1",
			AuthoredAt:    time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
			Entity:        &EntityRef{Kind: "txn", ID: "T1"},
			ParentVersion: &parent,
			Payload:       json.RawMessage(`{"category":"groceries"}`),
		},
		// A parent-free fact: no entity, null parent_version.
		{
			V:          SchemaVersion,
			Type:       OpRateSet,
			OpID:       "01J000000000000000000000R1",
			AuthoredAt: time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
			Payload:    json.RawMessage(`{"currency":"USD","rate_micro":"3672500"}`),
		},
	}
}

func mustEncodeBlob(t *testing.T, ops []Op) []byte {
	t.Helper()
	b, err := EncodeBlob(ops)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func goldenRawBody() RawBody {
	return RawBody{
		IngestID:   strings.Repeat("a", 64),
		ReceivedAt: time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
		RawBase64:  "aGk=",
	}
}

func goldenCheckpointHeads() []CheckpointHead {
	return []CheckpointHead{
		{WriterID: "ingest", Stream: "hot", Counter: "9", Hash: strings.Repeat("b", 64)},
		{WriterID: "dev-a", Stream: "hot", Counter: "12", Hash: strings.Repeat("c", 64)},
		{WriterID: "ingest", Stream: "cold", Counter: "9", Hash: strings.Repeat("d", 64)},
	}
}

// incompressibleBytes returns n bytes gzip cannot shrink, derived from a hash
// chain so the value is identical on every machine and every Go release. A
// math/rand stream is not: its algorithm is a documented implementation detail
// and the global source is randomly seeded since Go 1.20.
func incompressibleBytes(n int) []byte {
	out := make([]byte, 0, n+sha256.Size)
	var ctr [8]byte
	for i := uint64(0); len(out) < n; i++ {
		binary.BigEndian.PutUint64(ctr[:], i)
		sum := sha256.Sum256(ctr[:])
		out = append(out, sum[:]...)
	}
	return out[:n]
}

// prePadLength reports the framed length before bucket padding, derived from
// the frozen layout via the package's own SealedRegion so the test does not
// restate offsets.
func prePadLength(t *testing.T, b []byte) int {
	t.Helper()
	start, end, err := blob.SealedRegion(b)
	if err != nil {
		t.Fatalf("sealed region: %v", err)
	}
	payloadLen := int(binary.BigEndian.Uint32(b[start : start+4]))
	if start+4+payloadLen > end {
		t.Fatalf("payload length %d runs past the sealed region", payloadLen)
	}
	return start + 4 + payloadLen + blob.TagSize
}

// bucketEdgePlaintext finds a plaintext whose framed length lands exactly one
// byte under bucket bucketIdx, i.e. a blob with exactly one padding byte.
//
// It is the fixture that catches an off-by-one anywhere in the offset math:
// an ordinary fixture has hundreds of bytes of slack, so a reader that
// miscounted the header by one would still find the payload.
//
// gzip of incompressible input runs about len+18, and the framing overhead is
// ~83, so the answer is near bucket-101; the window is wide enough to absorb
// deflate's block accounting without scanning the whole bucket.
func bucketEdgePlaintext(t *testing.T, e blob.Envelope, bucketIdx int) []byte {
	t.Helper()
	bucket := blob.Buckets[bucketIdx]
	target := bucket - 1
	var sealer blob.PlaintextSealer
	for n := bucket - 200; n < bucket; n++ {
		if n < 1 {
			continue
		}
		pt := incompressibleBytes(n)
		s, err := sealer.Seal(e, pt)
		if err != nil {
			continue
		}
		if s.SizeBucket < bucket {
			continue // still fits a smaller rung
		}
		if s.SizeBucket > bucket {
			break // overshot this rung entirely
		}
		if prePadLength(t, s.Bytes) == target {
			return pt
		}
	}
	t.Fatalf("no plaintext frames to exactly %d bytes (bucket %d)", target, bucket)
	return nil
}

// escapeTrapOps is an op whose payload holds every character the two encoders
// treat differently, in the Go->TypeScript direction. Go's encoding/json escapes
// <, >, & and U+2028/U+2029 as \uXXXX; JSON.stringify emits them literally. The
// TypeScript side has a mirror fixture; without this one the asymmetry was only
// ever exercised in the direction where Go is the READER.
func escapeTrapOps() []Op {
	parent := int64(1)
	return []Op{{
		V:             SchemaVersion,
		Type:          OpTxnEdited,
		OpID:          "01J000000000000000000000G1",
		AuthoredAt:    time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
		Entity:        &EntityRef{Kind: "txn", ID: "T1"},
		ParentVersion: &parent,
		Payload: json.RawMessage(`{"merchant_raw":"كارفور",` +
			`"note":"Smith & Sons <flagged> \u2028 second line \u2029 end",` +
			`"amount_minor":"25000"}`),
	}}
}

// TestWriteConformanceFixtures regenerates the committed fixtures. It is opt-in
// (see writeFixturesEnv) because a golden file the test suite rewrites on every
// run is not a golden file.
//
//	LEDGER_WRITE_CONFORMANCE=1 go test ./internal/v2/oplog/ -run TestWriteConformanceFixtures -v
func TestWriteConformanceFixtures(t *testing.T) {
	if os.Getenv(writeFixturesEnv) != "1" {
		t.Skipf("set %s=1 to regenerate conformance/blob and conformance/op", writeFixturesEnv)
	}

	blobDir := filepath.Join(conformanceDir(), "blob")
	opDir := filepath.Join(conformanceDir(), "op")
	for _, d := range []string{blobDir, opDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}

	ops, err := EncodeBlob(goldenOps())
	if err != nil {
		t.Fatal(err)
	}
	raw, err := EncodeRawBody(goldenRawBody())
	if err != nil {
		t.Fatal(err)
	}
	checkpoint, err := EncodeCheckpointPayload(goldenCheckpointHeads())
	if err != nil {
		t.Fatal(err)
	}

	edgeEnv := blob.Envelope{UserID: conformanceUser, Stream: blob.StreamHot, WriterID: "dev-a", WriterCounter: 8}
	bigEdgeEnv := blob.Envelope{UserID: conformanceUser, Stream: blob.StreamHot, WriterID: "dev-a", WriterCounter: 12}
	type spec struct {
		file      string
		note      string
		kind      string
		env       blob.Envelope
		plaintext []byte
	}
	specs := []spec{
		{
			file:      "hot-dev-a-7.bin",
			note:      "a hot op blob: the golden op JSON of TestGoldenOpBytes, sealed at (dev-a, hot, 7)",
			kind:      KindOps,
			env:       blob.Envelope{UserID: conformanceUser, Stream: blob.StreamHot, WriterID: "dev-a", WriterCounter: 7},
			plaintext: ops,
		},
		{
			file:      "cold-ingest-3.bin",
			note:      "a cold raw-body blob: invariant I16 says this stream never carries ops",
			kind:      KindRawBody,
			env:       blob.Envelope{UserID: conformanceUser, Stream: blob.StreamCold, WriterID: IngestWriterID, WriterCounter: 3},
			plaintext: raw,
		},
		{
			file:      "hot-dev-a-8-bucket-edge.bin",
			note:      "a blob framed to exactly one byte under the 1 KiB bucket: one padding byte, so an off-by-one in any offset is fatal",
			kind:      KindRawBody,
			env:       edgeEnv,
			plaintext: nil, // filled in below; it depends on the envelope's AAD length
		},
		{
			file:      "hot-dev-a-11-escapes.bin",
			note:      "an op payload holding every character Go escapes and JSON.stringify does not, plus non-ASCII: the Go->TypeScript direction of that asymmetry",
			kind:      KindOps,
			env:       blob.Envelope{UserID: conformanceUser, Stream: blob.StreamHot, WriterID: "dev-a", WriterCounter: 11},
			plaintext: mustEncodeBlob(t, escapeTrapOps()),
		},
		{
			file:      "hot-dev-a-12-bucket-edge-4k.bin",
			note:      "one byte under rung 1 of the ladder: without it every fixture sits in bucket 0 and no blob crosses the executor boundary on a higher rung",
			kind:      "",
			env:       bigEdgeEnv,
			plaintext: nil, // filled in below
		},
	}
	// Both edge fixtures are raw bytes rather than records, so they carry no
	// kind, and their plaintexts depend on their envelope's AAD length.
	specs[2].plaintext = bucketEdgePlaintext(t, edgeEnv, 0)
	specs[2].kind = ""
	specs[4].plaintext = bucketEdgePlaintext(t, bigEdgeEnv, 1)

	var sealer blob.PlaintextSealer
	man := blobManifest{
		Note: "Sealed by internal/v2/oplog TestWriteConformanceFixtures. " +
			"Regenerate with LEDGER_WRITE_CONFORMANCE=1; do not hand-edit. " +
			"Both executors open these bytes; the framing is frozen (see internal/v2/blob).",
		Buckets:     blob.Buckets,
		NonceSize:   blob.NonceSize,
		TagSize:     blob.TagSize,
		ZeroHashHex: hex.EncodeToString(blob.ZeroHash[:]),
	}
	for _, s := range specs {
		sealed, err := sealer.Seal(s.env, s.plaintext)
		if err != nil {
			t.Fatalf("%s: %v", s.file, err)
		}
		if err := os.WriteFile(filepath.Join(blobDir, s.file), sealed.Bytes, 0o644); err != nil {
			t.Fatal(err)
		}
		man.Fixtures = append(man.Fixtures, blobFixture{
			File: s.file,
			Note: s.note,
			Kind: s.kind,
			Envelope: fixtureEnvelope{
				UserID:        s.env.UserID.String(),
				Stream:        s.env.Stream,
				WriterID:      s.env.WriterID,
				WriterCounter: strconv.FormatInt(s.env.WriterCounter, 10),
			},
			ExpectAAD:             string(s.env.AAD()),
			ExpectBucket:          sealed.SizeBucket,
			ExpectPlaintextBase64: base64.StdEncoding.EncodeToString(s.plaintext),
			ExpectPrePadLength:    prePadLength(t, sealed.Bytes),
		})
	}

	// The chain vector, generated rather than transcribed. chain_test.go pins
	// the same two hashes against literals, so the two must agree here.
	prev := blob.ZeroHash
	for _, step := range []struct {
		fill byte
		n    int
	}{{0xab, 1024}, {0xcd, 1024}} {
		body := bytes.Repeat([]byte{step.fill}, step.n)
		h := blob.Hash(prev, blob.Sealed{Bytes: body, SizeBucket: step.n})
		man.ChainSteps = append(man.ChainSteps, chainStep{
			FillByte:   hex.EncodeToString([]byte{step.fill}),
			Length:     step.n,
			ExpectHash: hex.EncodeToString(h[:]),
		})
		prev = h
	}
	writeJSONFixture(t, filepath.Join(blobDir, "manifest.json"), man)

	opMan := opManifest{
		Note: "Encoded by internal/v2/oplog TestWriteConformanceFixtures. " +
			"parent_version is a raw JSON NUMBER on the wire and a decimal string in this manifest; " +
			"money and counters are decimal strings on the wire. " +
			"authored_at_cases pin PARSED INSTANTS, never strings: Go's RFC3339Nano trims trailing " +
			"zeros where JavaScript's toISOString pads to three digits.",
		SchemaVersion:          SchemaVersion,
		GoldenOpsBase64:        base64.StdEncoding.EncodeToString(ops),
		GoldenRawBodyBase64:    base64.StdEncoding.EncodeToString(raw),
		GoldenCheckpointBase64: base64.StdEncoding.EncodeToString(checkpoint),
	}
	for _, ty := range Types {
		opMan.Types = append(opMan.Types, string(ty))
		if ty.ParentFree() {
			opMan.ParentFree = append(opMan.ParentFree, string(ty))
		}
	}
	decoded, err := DecodeBlob(ops)
	if err != nil {
		t.Fatal(err)
	}
	for _, o := range decoded {
		e := opExpect{
			Type:             string(o.Type),
			OpID:             o.OpID,
			AuthoredAtUnixMs: strconv.FormatInt(o.AuthoredAt.UnixMilli(), 10),
			HasEntity:        o.Entity != nil,
			IngestID:         o.IngestID,
		}
		if o.ParentVersion != nil {
			s := strconv.FormatInt(*o.ParentVersion, 10)
			e.ParentVersion = &s
		}
		opMan.ExpectOps = append(opMan.ExpectOps, e)
	}
	// The sub-millisecond, offset and leap-year cases, decoded by this build.
	// TestDecodeTruncatesAuthoredAtToMilliseconds asserts the same rule against
	// Go literals; here the answers are handed to the other executor.
	for _, wire := range timeAcceptCases {
		got, err := DecodeBlob(timeProbeBlob(wire))
		if err != nil {
			t.Fatalf("%s: %v", wire, err)
		}
		opMan.AuthoredAtCases = append(opMan.AuthoredAtCases, timeCase{
			Wire:         wire,
			ExpectUnixMs: strconv.FormatInt(got[0].AuthoredAt.UnixMilli(), 10),
		})
	}
	// The parent_version asymmetry, encoded by this executor so the other can
	// check it refuses exactly these bytes.
	overflow := int64(1)<<53 + 1
	overflowBlob, err := EncodeBlob([]Op{{
		V:             SchemaVersion,
		Type:          OpTxnCategorized,
		OpID:          "01J000000000000000000000P1",
		AuthoredAt:    time.Date(2026, 6, 5, 10, 0, 0, 0, time.UTC),
		Entity:        &EntityRef{Kind: "txn", ID: "T1"},
		ParentVersion: &overflow,
		Payload:       json.RawMessage(`{"category":"groceries"}`),
	}})
	if err != nil {
		t.Fatal(err)
	}
	opMan.ParentVersionOverflowBase64 = base64.StdEncoding.EncodeToString(overflowBlob)
	opMan.ParentVersionOverflow = strconv.FormatInt(overflow, 10)

	for _, wire := range timeRejectCases {
		if _, err := DecodeBlob(timeProbeBlob(wire)); err == nil {
			t.Fatalf("authored_at %q must be refused before it can be written as a reject case", wire)
		}
		opMan.AuthoredAtRejects = append(opMan.AuthoredAtRejects, wire)
	}
	writeJSONFixture(t, filepath.Join(opDir, "manifest.json"), opMan)
}

// timeProbeBlob is a minimal one-op blob carrying an arbitrary authored_at
// string, used to ask each executor what instant it reads out of it.
func timeProbeBlob(wire string) []byte {
	return []byte(`{"v":1,"kind":"ops","ops":[{"v":1,"type":"rate_set",` +
		`"op_id":"01J000000000000000000000R1","authored_at":"` + wire + `",` +
		`"parent_version":null,"payload":{}}]}`)
}

func writeJSONFixture(t *testing.T, path string, v any) {
	t.Helper()
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, append(b, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
}

// ---------------------------------------------------------------------------
// The always-on halves: this build must still agree with what it wrote, and
// with what the other executor writes.
// ---------------------------------------------------------------------------

func readBlobManifest(t *testing.T, dir string) blobManifest {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, "manifest.json"))
	if err != nil {
		// Not a skip. A missing fixture set means the cross-executor gate is not
		// running, and a gate that silently disables itself is worse than no gate.
		t.Fatalf("conformance manifest is missing (%v); regenerate with %s=1", err, writeFixturesEnv)
	}
	var man blobManifest
	if err := json.Unmarshal(b, &man); err != nil {
		t.Fatal(err)
	}
	if len(man.Fixtures) == 0 {
		t.Fatal("conformance manifest lists no fixtures")
	}
	return man
}

// checkFixtures opens every fixture in dir and asserts it still yields the
// pinned plaintext at the pinned position. It is shared by the Go-authored and
// the TypeScript-authored sets: the assertion is the same in both directions,
// which is the point of a frozen format.
func checkFixtures(t *testing.T, dir string) {
	t.Helper()
	man := readBlobManifest(t, dir)
	var sealer blob.PlaintextSealer
	for _, f := range man.Fixtures {
		t.Run(f.File, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(dir, f.File))
			if err != nil {
				t.Fatal(err)
			}
			if len(raw) != f.ExpectBucket {
				t.Fatalf("blob is %d bytes, manifest says bucket %d", len(raw), f.ExpectBucket)
			}
			env := f.Envelope.blobEnvelope(t)
			if got := string(env.AAD()); got != f.ExpectAAD {
				t.Fatalf("AAD is %q, manifest says %q", got, f.ExpectAAD)
			}
			if embedded, err := blob.EmbeddedAAD(raw); err != nil {
				t.Fatalf("embedded AAD: %v", err)
			} else if string(embedded) != f.ExpectAAD {
				t.Fatalf("embedded AAD is %q, manifest says %q", embedded, f.ExpectAAD)
			}
			if got := prePadLength(t, raw); got != f.ExpectPrePadLength {
				t.Fatalf("framed length before padding is %d, manifest says %d", got, f.ExpectPrePadLength)
			}

			plaintext, err := sealer.Open(env, blob.Sealed{Bytes: raw, SizeBucket: len(raw)})
			if err != nil {
				t.Fatalf("open: %v", err)
			}
			want, err := base64.StdEncoding.DecodeString(f.ExpectPlaintextBase64)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(plaintext, want) {
				t.Fatalf("plaintext differs from the manifest:\n got %q\nwant %q", plaintext, want)
			}

			// Moving the blob one position along must be refused. Without this
			// the whole fixture set would pass against an Open that ignored the
			// AAD entirely.
			moved := env
			moved.WriterCounter++
			if _, err := sealer.Open(moved, blob.Sealed{Bytes: raw, SizeBucket: len(raw)}); err == nil {
				t.Fatal("opening the fixture at the next counter must fail")
			}

			switch f.Kind {
			case KindOps:
				if _, err := DecodeBlob(plaintext); err != nil {
					t.Fatalf("decode ops: %v", err)
				}
				if _, err := DecodeRawBody(plaintext); err == nil {
					t.Fatal("an op blob must not decode as a raw body (invariant I16)")
				}
			case KindRawBody:
				rb, err := DecodeRawBody(plaintext)
				if err != nil {
					t.Fatalf("decode raw body: %v", err)
				}
				// The PAYLOAD is decoded, not just the record around it.
				// DecodeRawBody used to hand back RawBase64 as an unexamined
				// string, and this check only called DecodeRawBody — so the cold
				// record's actual content never crossed the executor boundary at
				// all, and a TypeScript encoder emitting unpadded base64url
				// passed this gate green.
				raw, err := base64.StdEncoding.DecodeString(rb.RawBase64)
				if err != nil {
					t.Fatalf("raw_base64 does not decode: %v", err)
				}
				if len(raw) == 0 {
					t.Fatal("cold fixtures must carry a non-empty body, or this check proves nothing")
				}
				if got := base64.StdEncoding.EncodeToString(raw); got != rb.RawBase64 {
					t.Fatalf("raw_base64 is not canonical standard base64:\n got %s\nwant %s", rb.RawBase64, got)
				}
				if _, err := DecodeBlob(plaintext); err == nil {
					t.Fatal("a raw-body blob must not decode as ops (invariant I16)")
				}
			}
		})
	}
}

// TestConformanceFixturesAreWhatThisBuildProduces is the Go half of the
// dual-executor gate: the committed bytes must still open, at the same
// positions, to the same plaintexts, under this build.
func TestConformanceFixturesAreWhatThisBuildProduces(t *testing.T) {
	dir := filepath.Join(conformanceDir(), "blob")
	checkFixtures(t, dir)

	man := readBlobManifest(t, dir)
	// The layout constants travel in the manifest so the TypeScript port has one
	// source for them rather than a hand-copied ladder.
	if len(man.Buckets) != len(blob.Buckets) {
		t.Fatalf("manifest lists %d buckets, this build has %d", len(man.Buckets), len(blob.Buckets))
	}
	for i, b := range blob.Buckets {
		if man.Buckets[i] != b {
			t.Fatalf("bucket %d is %d, manifest says %d", i, b, man.Buckets[i])
		}
	}
	if man.NonceSize != blob.NonceSize || man.TagSize != blob.TagSize {
		t.Fatalf("reserved slot sizes moved: manifest has nonce %d tag %d, build has %d/%d",
			man.NonceSize, man.TagSize, blob.NonceSize, blob.TagSize)
	}
	if man.ZeroHashHex != hex.EncodeToString(blob.ZeroHash[:]) {
		t.Fatalf("chain genesis moved: manifest %s", man.ZeroHashHex)
	}

	prev := blob.ZeroHash
	for i, step := range man.ChainSteps {
		fill, err := hex.DecodeString(step.FillByte)
		if err != nil || len(fill) != 1 {
			t.Fatalf("chain step %d has fill byte %q", i, step.FillByte)
		}
		body := bytes.Repeat(fill, step.Length)
		h := blob.Hash(prev, blob.Sealed{Bytes: body, SizeBucket: step.Length})
		if got := hex.EncodeToString(h[:]); got != step.ExpectHash {
			t.Fatalf("chain step %d hashes to %s, manifest says %s", i, got, step.ExpectHash)
		}
		prev = h
	}
	if len(man.ChainSteps) == 0 {
		t.Fatal("the manifest carries no chain vector")
	}
}

// TestOpConformanceManifestMatchesThisBuild does the same for the op wire
// model: the golden bytes must still encode and decode identically here.
func TestOpConformanceManifestMatchesThisBuild(t *testing.T) {
	b, err := os.ReadFile(filepath.Join(conformanceDir(), "op", "manifest.json"))
	if err != nil {
		t.Fatalf("op manifest is missing (%v); regenerate with %s=1", err, writeFixturesEnv)
	}
	var man opManifest
	if err := json.Unmarshal(b, &man); err != nil {
		t.Fatal(err)
	}
	if man.SchemaVersion != SchemaVersion {
		t.Fatalf("manifest is for schema v%d, this build is v%d", man.SchemaVersion, SchemaVersion)
	}
	if len(man.Types) != len(Types) {
		t.Fatalf("manifest lists %d op types, this build has %d", len(man.Types), len(Types))
	}
	for i, ty := range Types {
		if man.Types[i] != string(ty) {
			t.Fatalf("op type %d is %q, manifest says %q", i, ty, man.Types[i])
		}
	}
	for _, ty := range man.ParentFree {
		if !OpType(ty).ParentFree() {
			t.Fatalf("manifest calls %q parent-free and this build does not", ty)
		}
	}

	ops, err := EncodeBlob(goldenOps())
	if err != nil {
		t.Fatal(err)
	}
	if got := base64.StdEncoding.EncodeToString(ops); got != man.GoldenOpsBase64 {
		want, _ := base64.StdEncoding.DecodeString(man.GoldenOpsBase64)
		t.Fatalf("op blob encoding changed:\n got %s\nwant %s", ops, want)
	}
	raw, err := EncodeRawBody(goldenRawBody())
	if err != nil {
		t.Fatal(err)
	}
	if got := base64.StdEncoding.EncodeToString(raw); got != man.GoldenRawBodyBase64 {
		t.Fatalf("raw body encoding changed: %s", raw)
	}
	cp, err := EncodeCheckpointPayload(goldenCheckpointHeads())
	if err != nil {
		t.Fatal(err)
	}
	if got := base64.StdEncoding.EncodeToString(cp); got != man.GoldenCheckpointBase64 {
		t.Fatalf("checkpoint payload encoding changed: %s", cp)
	}

	decoded, err := DecodeBlob(ops)
	if err != nil {
		t.Fatal(err)
	}
	if len(decoded) != len(man.ExpectOps) {
		t.Fatalf("golden blob has %d ops, manifest expects %d", len(decoded), len(man.ExpectOps))
	}
	for i, want := range man.ExpectOps {
		got := decoded[i]
		if string(got.Type) != want.Type || got.OpID != want.OpID {
			t.Fatalf("op %d is %s/%s, manifest says %s/%s", i, got.Type, got.OpID, want.Type, want.OpID)
		}
		if ms := strconv.FormatInt(got.AuthoredAt.UnixMilli(), 10); ms != want.AuthoredAtUnixMs {
			t.Fatalf("op %d authored at %s ms, manifest says %s", i, ms, want.AuthoredAtUnixMs)
		}
		if (got.Entity != nil) != want.HasEntity {
			t.Fatalf("op %d entity presence disagrees with the manifest", i)
		}
		if got.IngestID != want.IngestID {
			t.Fatalf("op %d ingest_id is %q, manifest says %q", i, got.IngestID, want.IngestID)
		}
		switch {
		case got.ParentVersion == nil && want.ParentVersion != nil:
			t.Fatalf("op %d has no parent_version, manifest says %s", i, *want.ParentVersion)
		case got.ParentVersion != nil && want.ParentVersion == nil:
			t.Fatalf("op %d has parent_version %d, manifest says null", i, *got.ParentVersion)
		case got.ParentVersion != nil && strconv.FormatInt(*got.ParentVersion, 10) != *want.ParentVersion:
			t.Fatalf("op %d parent_version is %d, manifest says %s", i, *got.ParentVersion, *want.ParentVersion)
		}
	}

	if len(man.AuthoredAtCases) == 0 {
		t.Fatal("the manifest carries no authored_at cases")
	}
	for _, c := range man.AuthoredAtCases {
		got, err := DecodeBlob(timeProbeBlob(c.Wire))
		if err != nil {
			t.Fatalf("%s: %v", c.Wire, err)
		}
		if ms := strconv.FormatInt(got[0].AuthoredAt.UnixMilli(), 10); ms != c.ExpectUnixMs {
			t.Fatalf("%s decodes to %s ms, manifest says %s", c.Wire, ms, c.ExpectUnixMs)
		}
	}
	// Go reads the overflow blob exactly; TypeScript must refuse it. Asserting
	// the Go half here is what makes the TypeScript refusal meaningful rather
	// than a test of a string nobody produces.
	overflowBlob, err := base64.StdEncoding.DecodeString(man.ParentVersionOverflowBase64)
	if err != nil {
		t.Fatal(err)
	}
	overflowOps, err := DecodeBlob(overflowBlob)
	if err != nil {
		t.Fatalf("the parent_version overflow blob must decode HERE: %v", err)
	}
	if len(overflowOps) != 1 || overflowOps[0].ParentVersion == nil {
		t.Fatal("the parent_version overflow blob lost its parent_version")
	}
	if got := strconv.FormatInt(*overflowOps[0].ParentVersion, 10); got != man.ParentVersionOverflow {
		t.Fatalf("parent_version decoded as %s, manifest says %s", got, man.ParentVersionOverflow)
	}

	if len(man.AuthoredAtRejects) != len(timeRejectCases) {
		t.Fatalf("the manifest lists %d reject cases, this build has %d", len(man.AuthoredAtRejects), len(timeRejectCases))
	}
	for _, wire := range man.AuthoredAtRejects {
		if _, err := DecodeBlob(timeProbeBlob(wire)); err == nil {
			t.Fatalf("authored_at %q must be refused: the manifest promises the TypeScript executor refuses it", wire)
		}
	}
}

// TestTypeScriptSealedBlobsOpenInGo closes the direction a Go-authored fixture
// set cannot: a TypeScript port that reads Go's bytes perfectly and WRITES
// subtly wrong ones passes every other test in this file, and would then be
// discovered by the server rejecting a device's uploads — or worse, by the
// server accepting them and no other device being able to open them.
//
// The fixtures are produced by `cd client && bun run gen-fixtures` and
// committed; that script also asserts the bytes it is about to write are the
// bytes the current TypeScript produces, so a stale set fails on the TS side.
func TestTypeScriptSealedBlobsOpenInGo(t *testing.T) {
	dir := filepath.Join(conformanceDir(), "ts")
	checkFixtures(t, dir)

	// And the ops inside must be the ops the TypeScript claimed to write. The
	// comparison is on values, never on bytes: Go escapes <, > and & as <
	// and friends where JSON.stringify does not, so the two encoders produce
	// different bytes for the same op — which is exactly why the ampersand
	// fixture is in the set.
	var sealer blob.PlaintextSealer
	man := readBlobManifest(t, dir)
	found := 0
	for _, f := range man.Fixtures {
		if f.Kind != KindOps {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(dir, f.File))
		if err != nil {
			t.Fatal(err)
		}
		plaintext, err := sealer.Open(f.Envelope.blobEnvelope(t), blob.Sealed{Bytes: raw, SizeBucket: len(raw)})
		if err != nil {
			t.Fatalf("%s: %v", f.File, err)
		}
		ops, err := DecodeBlob(plaintext)
		if err != nil {
			t.Fatalf("%s: %v", f.File, err)
		}
		if len(ops) == 0 {
			t.Fatalf("%s: TypeScript wrote an empty op blob", f.File)
		}
		found++

		if f.File == "ts-hot-dev-a-7.bin" {
			want := goldenOps()
			if len(ops) != len(want) {
				t.Fatalf("%s: %d ops, want %d", f.File, len(ops), len(want))
			}
			for i := range want {
				if ops[i].Type != want[i].Type || ops[i].OpID != want[i].OpID {
					t.Fatalf("%s: op %d is %s/%s, want %s/%s", f.File, i, ops[i].Type, ops[i].OpID, want[i].Type, want[i].OpID)
				}
				if !ops[i].AuthoredAt.Equal(want[i].AuthoredAt) {
					t.Fatalf("%s: op %d authored at %v, want %v — the two executors must read the same INSTANT",
						f.File, i, ops[i].AuthoredAt, want[i].AuthoredAt)
				}
				if (ops[i].ParentVersion == nil) != (want[i].ParentVersion == nil) {
					t.Fatalf("%s: op %d parent_version presence differs", f.File, i)
				}
				if ops[i].ParentVersion != nil && *ops[i].ParentVersion != *want[i].ParentVersion {
					t.Fatalf("%s: op %d parent_version is %d, want %d", f.File, i, *ops[i].ParentVersion, *want[i].ParentVersion)
				}
				if (ops[i].Entity == nil) != (want[i].Entity == nil) {
					t.Fatalf("%s: op %d entity presence differs", f.File, i)
				}
				if ops[i].Entity != nil && (ops[i].Entity.Kind != want[i].Entity.Kind || ops[i].Entity.ID != want[i].Entity.ID) {
					t.Fatalf("%s: op %d entity is %+v, want %+v", f.File, i, ops[i].Entity, want[i].Entity)
				}
				if ops[i].IngestID != want[i].IngestID {
					t.Fatalf("%s: op %d ingest_id is %q, want %q", f.File, i, ops[i].IngestID, want[i].IngestID)
				}
				var gotPayload, wantPayload any
				if err := json.Unmarshal(ops[i].Payload, &gotPayload); err != nil {
					t.Fatal(err)
				}
				if err := json.Unmarshal(want[i].Payload, &wantPayload); err != nil {
					t.Fatal(err)
				}
				if !jsonEqual(gotPayload, wantPayload) {
					t.Fatalf("%s: op %d payload is %s, want %s", f.File, i, ops[i].Payload, want[i].Payload)
				}
			}
		}

		if f.File == "ts-hot-dev-a-9-escapes.bin" {
			// The escaping fixture: Go must read back the exact strings the
			// TypeScript wrote, including the characters Go's own encoder would
			// have escaped.
			var payload struct {
				Merchant string `json:"merchant_raw"`
				Note     string `json:"note"`
			}
			if err := json.Unmarshal(ops[0].Payload, &payload); err != nil {
				t.Fatal(err)
			}
			// U+2028 is in the set on purpose: Go's encoder escapes it and
			// JSON.stringify does not, so it is the sharpest form of the
			// escaping asymmetry this fixture exists to prove is harmless.
			for _, want := range []string{"&", "<", ">", "\u2028"} {
				if !strings.Contains(payload.Note, want) {
					t.Fatalf("%s: note %q lost %q in transit", f.File, payload.Note, want)
				}
			}
			if payload.Merchant != "كارفور" {
				t.Fatalf("%s: merchant is %q, want the Arabic original", f.File, payload.Merchant)
			}
		}
	}
	if found < 2 {
		t.Fatalf("expected at least two TypeScript-authored op blobs, found %d", found)
	}
}

// jsonEqual compares two decoded JSON values structurally.
func jsonEqual(a, b any) bool {
	x, errA := json.Marshal(a)
	y, errB := json.Marshal(b)
	return errA == nil && errB == nil && bytes.Equal(x, y)
}
